### ISSUE TITLE
Add back the RSS feed to local messages

### ISSUE THREAD

**Issue by ialbert** [ialbert/biostar-central#228]
The ability to obtain a feed to local messages has been lost in the transition

**Comment by iCHAIT** [comment]
I have a solution in mind: Display a "Messages Feed" link on /info/rss/ 
that links to /feeds/messages/ and will only be displayed when
the user is logged in.

We can then create a new class in `biostar.server.feeds` which returns 
the messages rss.

Any thoughts?

**Comment by ialbert** [comment]
we have moved to a new codebase, these issues do not apply anymore.
