### ISSUE TITLE
"Forum" tag automatically added even if already present

### ISSUE THREAD

**Issue by nimiq** [ialbert/biostar-central#231]
When editing a "forum" post, the tag "Forum" is automatically added, even in case it is already present. Maybe it is only a matter of case-sensitive comparison.
![screen shot 2014-05-09 at 3 48 22 pm](https://cloud.githubusercontent.com/assets/6423485/2928757/585f3566-d781-11e3-8704-c3f71e9ba29f.png)

**Comment by iCHAIT** [comment]
The behaviour is similar for not only Forum but all  the other tags also.

**Comment by ialbert** [comment]
This has been fixed but the issue was not closed.
