### ISSUE TITLE
Links to other posts automatically use post's title as text

### ISSUE THREAD

**Issue by nimiq** [ialbert/biostar-central#232]
When linking to another post or page, the title of that page is automatically fetched and used as text of the link.
I am not sure if this is really what a user expects to happen.

Example. How the link looks like while editing:
![screen shot 2014-05-09 at 3 57 45 pm](https://cloud.githubusercontent.com/assets/6423485/2928896/fb09e698-d782-11e3-8d25-d19d14d84290.png)

How the link looks like when saved:
![screen shot 2014-05-09 at 3 58 17 pm](https://cloud.githubusercontent.com/assets/6423485/2928901/047e803a-d783-11e3-86bb-4fd07bfa1f04.png)

**Comment by ialbert** [comment]
This has been fixed but forgot to close the issue.
