### ISSUE TITLE
Mobile site doesn't display votes

### ISSUE THREAD

**Issue by mdshw5** [ialbert/biostar-central#238]
The mobile site only displays vote counts on comments, not answers.

**Comment by Gig77** [comment]
Yes, please fix, this prevents me a lot from voting since I almost exclusively read on my mobile.

**Comment by tvvocold** [comment]
@ialbert

**Comment by sestaton** [comment]
+1 It would be nice to see the votes and cast votes on mobile. All that is displayed is the question text with the 'similar posts' section below (at least on Android with Firefox and Chrome, though this is probably not OS-specific).

**Comment by alevchuk** [comment]
Yep, that's still true :(

![img_4159](https://cloud.githubusercontent.com/assets/64738/20021042/682d3e9c-a291-11e6-8781-e4dbd3c4e656.PNG)

![img_4160](https://cloud.githubusercontent.com/assets/64738/20021104/a20db376-a291-11e6-9b98-7506d3035e87.PNG)

**Comment by Natay** [comment]
This issue has been fixed in the most current release of biostars.
