### ISSUE TITLE
keep sort-by preference in a cookie

### ISSUE THREAD

**Issue by brentp** [ialbert/biostar-central#251]
I often want to sort by creation instead of the default of 'update'. It always loses this preference as I navigate the site and when I come back to it.

It would be nice to remember the user's preference in a cookie and default to that instead of defaulting to 'update'.

**Comment by ialbert** [comment]
We are on a cleanup mission to revisit and close issues. 

This is not done so since it can be very confusing for someone that does a search, goes away and comes back sees a different site than someone on a computer next to them.
