### ISSUE TITLE
IP address issue when using a reverse proxy

### ISSUE THREAD

**Issue by nimiq** [ialbert/biostar-central#260]
In Neurostars staging env (and in the future also live) we use Nginx as reverse proxy and Waitress as web server. In such a configuration the HTTP headers of clients are:

- `request.META['REMOTE_ADDR']` = 'localhost', probably because of the reverse proxy;
- `request.META['HTTP_X_FORWARDED_FOR']` = the real IP address of the client.

This situation messes up with the code [here](https://github.com/ialbert/biostar-central/blob/master/biostar/apps/posts/models.py#L341) and ends up in an exception [here](https://github.com/ialbert/biostar-central/blob/master/biostar/apps/posts/models.py#L350) because ip='localhost' which is not a valid IP address.

**Comment by ialbert** [comment]
this is actually fixed.
