### ISSUE TITLE
Bug in html link parsing

### ISSUE THREAD

**Issue by enormandeau** [ialbert/biostar-central#272]
When a user puts a link in parentheses in his post and does not identify it as an html link to the post editor, the link is automatically parsed but includes the closing parenthesis and does not work. I corrected 3 broken links in the past 24 hours and I looked only at about 10 threads.

For example, the phrase `(look at www.google.com)` would be badly parsed and the last parenthesis would be included in the html link.

**Comment by iCHAIT** [comment]
@ialbert I too tried reproducing this, but the link worked fine for me.

**Comment by ialbert** [comment]
There is one ongoing bug still due to the bleach.linkify (see below) but otherwise it should work well:

https://github.com/Bioconductor/support.bioconductor.org/issues/21
