### ISSUE TITLE
RSS feed for user bookmarks

### ISSUE THREAD

**Issue by mdshw5** [ialbert/biostar-central#273]
I should have a way to liberate my Biostars bookmarks so that I may, for example, add them as bookmarks to another service. RSS might be a good exchange format, and so Biostars would allow two things:
1. A user profile option to "make bookmarks public"
2. A routing endpoint for `/feed/user/UID/bookmarks`
3. # 2 also leads me to a point about how `/feed/user/UID` should be a root for:
   - `/feed/user/UID/posts`
   - `/feed/user/UID/torrents`
   - `/feed/user/UID/comments`
   - etc

**Comment by ialbert** [comment]
we have moved to a new codebase, these issues do not apply anymore.
