### ISSUE TITLE
[feature request 3.0] federation and decentralization

### ISSUE THREAD

**Issue by satra** [ialbert/biostar-central#285]
@ialbert - another feature that we kind of want to move towards but this may require serious re-architecting.

we would love for people to have their own instances of the biostar platform but queries can be federated across linked instances. 

i think biostars really has the potential to get people out of academic silos, but the answer cannot be (i think)  a single platform. it has to be a dynamic set of coordinated decentralized services.

i'm happy to post more details here as to what i'm envisioning, but figured i would get the conversation started.

**Comment by ialbert** [comment]
Continued here https://github.com/ialbert/biostar-central/issues/400
