### ISSUE TITLE
Threading in email notifications

### ISSUE THREAD

**Issue by tnabtaf** [ialbert/biostar-central#292]
In Biostar 2, email notifications of questions have a subject line of just the question:
  [galaxy-biostar] URGENT! Galaxy Account no longer accessible!! Please help ASAP!

Answers and comments put a leading character in the email subject.  For example:
  [galaxy-biostar] A: URGENT! Galaxy Account no longer accessible!! Please help ASAP!

Changing the subject line makes it difficult for most email clients to realize that both postings are part of the same thread.  It would be nice if Biostar could give clients some of hint that these postings are part of the same thread.  I think this can be done by
- Keeping the subject line the same
- Including "In-Reply-To", "References" and/or "Original-Message-ID" in the header.

See http://stackoverflow.com/questions/288757/how-to-identify-email-belongs-to-existing-thread-or-conversation

Thanks

**Comment by ialbert** [comment]
we have move to a new codebase, adding proper email threading is a bit out of scope, we may revisit at some time

**Comment by tnabtaf** [comment]
HI Istvan,

Congrats on the new code base!

Dave C
