### ISSUE TITLE
Reply to question via email is broken

### ISSUE THREAD

**Issue by mdshw5** [ialbert/biostar-central#293]
Probably related to email parsing mentioned in #254. The delivery report body is below. 

Final-Recipient: rfc822; biostar+028f57d1+code@biostars.io
Original-Recipient: rfc822;biostar+028f57d1+code@biostars.io
Action: failed
Status: 5.3.0
Diagnostic-Code: x-unix; sh: 1: /export/test.py: not found   % Total    %
   Received % Xferd  Average Speed   Time    Time     Time  Current
   Dload  Upload   Total   Spent    Left  Speed _  0     0    0     0    0
   0      0      0 --:--:-- --:--:-- --:--:--     0_100  6003    0    30  100
   5973    229  45706 --:--:-- --:--:-- --:--:-- 46664

**Comment by ialbert** [comment]
we have moved to a new codebase, these issues do not apply anymore.
