### ISSUE TITLE
[UI] Allow customization of top header categories

### ISSUE THREAD

**Issue by brainstorm** [ialbert/biostar-central#294]
_From @brainstorm on July 27, 2014 20:55_

As commented by Giovanni in: https://www.biostars.org/p/99956/#101306

The top categories header needs a better placement and customizability (other than editing some `.py` files)

![image](https://cloud.githubusercontent.com/assets/175587/3715112/1be73326-15d0-11e4-8eee-138946ce5514.png)

_Copied from original issue: INCF/biostar-central#50_

**Comment by ialbert** [comment]
The interface will be redesigned and the UI features needs to be revisited then in the larger context.
