### ISSUE TITLE
[UI] Email notifications too hidden

### ISSUE THREAD

**Issue by brainstorm** [ialbert/biostar-central#296]
_From @brainstorm on June 27, 2014 17:24_

Currently there's arguably many users that just miss the "getting notified by email" drop down menu on the questions.

![image](https://cloud.githubusercontent.com/assets/175587/3415332/dac30810-fe1f-11e3-9b93-a4b5d75c25f2.png)

Exposing it on a different way so that is more obvious to the user would improve the adoption of this feature (which helps on keeping users engaged on the site).

_Copied from original issue: INCF/biostar-central#42_

**Comment by ialbert** [comment]
The interface will be redesigned and the UI features needs to be revisited then in the larger context.
