### ISSUE TITLE
[UI] Comment sorting based on similarity or other metrics and allow consolidation of information

### ISSUE THREAD

**Issue by brainstorm** [ialbert/biostar-central#299]
_From @satra on June 27, 2014 18:45_

if comments can be sorted via multiple means (e.g., votes, similiarity), that might provide a way to merge or consolidate comments into better answers.

_Copied from original issue: INCF/biostar-central#45_

**Comment by ialbert** [comment]
Bisotar upgrade path: https://github.com/ialbert/biostar-central/issues/400
