### ISSUE TITLE
vote count on posts always zero on user page

### ISSUE THREAD

**Issue by sestaton** [ialbert/biostar-central#305]
If we go to our user page, let's consider [user number 2](https://www.biostars.org/u/2/) as an example, we can see a listing of the comment and answer activity for this user displayed along with the tally of votes, answers, and views on that particular post.

For each post, the vote count always says zero no matter how many votes have been earned or cast (or bookmarks made, which should also add to this count as I understand it now). I would think all the votes for a comment or an answer would be reflected, as they are on the "votes" tab (though not in numerical form there).

Am I wrong in thinking the votes should reflect the number of votes earned on that comment or answer for that one user? It looks like this does work for "Forum" posts, though not as I would expect. In that case, it seems the votes reflect the total for the whole thread.

Sorry if I'm misunderstanding this or if it's been discussed before.

**Comment by ialbert** [comment]
This has been fixed just never closed.

**Comment by sestaton** [comment]
I don't think this is fixed. If you click the link in the original post here, or view any user, all posts still show zero votes regardless of the number of votes.

**Comment by ialbert** [comment]
You're right this was merged into 3.0, I'll merge it into the current release as well.

**Comment by sestaton** [comment]
Thanks for the work on this!

**Comment by ialbert** [comment]
This has been enabled. It is still not entirely correct in that the reply counts still refer to the thread rather than the post. Turns out that needs a new separate fix since the replies are only tracked at question level. This will be refactored in a different way.

**Comment by Natay** [comment]
This has been fixed in the most current release of biostars, the reply count represents the replies to that answer/comment and not the whole thread
