### ISSUE TITLE
Moving deleted answer into a comment decrements answer count 

### ISSUE THREAD

**Issue by ialbert** [ialbert/biostar-central#307]
A deleted answer already decrements the answer count, moving it to a comment decrements one more time.

**Comment by RamRS** [comment]
Is it OK if I add my thoughts here? 

I did some digging, and we could probably not call `post.update_reply_count()` when the action is `MOVE_TO_ANSWER` or `MOVE_TO_COMMENT` in https://github.com/ialbert/biostar-central/blob/master/biostar/server/moderate.py

**Comment by RamRS** [comment]
I will not interfere then. Is there any way I can help with your current refactoring?

**Comment by Natay** [comment]
This issue has been fixed in the most current release of biostars.
