### ISSUE TITLE
Feature Request: list tweets associated to a post

### ISSUE THREAD

**Issue by lindenb** [ialbert/biostar-central#308]
As said Zev :
<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/yokofakun">@yokofakun</a> it would be cool if responding to a biostars tweet posted a comment.</p>&mdash; Zev Kronenberg (@zevkronenberg) <a href="https://twitter.com/zevkronenberg/status/540246025236389888">December 3, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

or, simplier, it would be nice to visualize some tweets linked to a post: something like https://dev.twitter.com/web/embedded-timelines#search ?

**Comment by ialbert** [comment]
We have embedded tweets and that solves some aspects of citing tweets. Watching a hashtag and posting automatically adds a different level of complexity to the code. We are on a mission to simplify as much as possible.
