### ISSUE TITLE
Scholar badge always associates to first accepted answer

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#309]
The scholar badge, under For:, always points to only the first accepted answer for a user. Shouldn't it point to a different answer each time the badge is awarded?

Example:
![Check out three of my answers](https://cloud.githubusercontent.com/assets/4529399/5599348/ec868da8-9292-11e4-823d-e007180ee7e3.png)

**Comment by ialbert** [comment]
Hm, indeed. Will look into it.

**Comment by hmontenegro** [comment]
The same happens with the "teacher" badge.

**Comment by ialbert** [comment]
these are all fixed in Biostar 3.0 I just need to make a final push to migrate to the new codebase.

**Comment by Natay** [comment]
This issue has been fixed in the most current version of Biostar
