### ISSUE TITLE
How could biostar.org do it?

### ISSUE THREAD

**Issue by tvvocold** [ialbert/biostar-central#310]
I  google “biostars” and got this: https://gogogo.cf/search?nord=1&q=biostars
How could biostars.org do this?(with a google inside search button and top tags in google'result page)
(I has a site use biostar 2.2.0 too,but it seems don't got a search result like that.
Also i checked the sitemap.xml in mine and it looks like the same as biostars.org'.)

BTW, the Biostar' seems don't got a best search result in google.com, Most of post wasn't found in page, So maybe biostar 3.0 could fix/improve it?

**Comment by martenson** [comment]
Biostar has great Google presence, mostly due to the structured data being used.
The link you provided leads to some captcha so I have no idea what you are linking to. Try a screenshot.

**Comment by tvvocold** [comment]
Emm,seems like the biostar' PR  make it, never mind. Thx!
