### ISSUE TITLE
Missing examples in live/deploy?

### ISSUE THREAD

**Issue by danking** [ialbert/biostar-central#311]
Hi there the deploy docs mention

```
Example files can be found in the live/deploy folder.
```

I don't see them in the master branch, nor on my local system after running the commands from the previous doc pages. Am I missing something or is this documentation out of date?

**Comment by tvvocold** [comment]
hi there,i believe the example env files locate in [conf folder](https://github.com/ialbert/biostar-central/tree/2.3/conf)

**Comment by Natay** [comment]
The example files for the most current version have been moved to:

https://github.com/ialbert/biostar-central/tree/master/conf/site
