### ISSUE TITLE
follow via email makes impossible to reply on site

### ISSUE THREAD

**Issue by duboism** [ialbert/biostar-central#312]
I used the option "follow via email" (in thread https://neurostars.org/p/2856/). I was then correctly notified of answers. The footer of the email states: "You may reply via email or visit http://neurostars.org/p/2856/#2859".
I tried to comment directly on the website but it didn't work (I have tried several times, waiting a few minutes between each trial; I haven't see any error message). I have tried to switch back to "Follow via local message" but it didn't work.
Reply by email worked. I can edit the posted comments too.

**Comment by duboism** [comment]
I have notified INCF webmaster (thought this might be a configuration issue on their side).

**Comment by brainstorm** [comment]
I'm confused by this one, I cannot reproduce it... which browser are you using? I'm on Chrome right now.

Can you paste some screenshots on what's happening?

Thanks for reporting!
