### ISSUE TITLE
High traffic deployment guide

### ISSUE THREAD

**Issue by poliveira89** [ialbert/biostar-central#313]
Hello,

I'm trying to deploy Biostars-Central on a "High Traffic deployment" alongside this small guide: http://docs.biostars.org/en/latest/deploy.html#high-traffic-deployment

But, I'm struggling with this, because I feel that there is a lot of information missing to connect all the dots. 

I have installed: nginx, redis, gunicorn, elastic search, postgresql, celery and supervisord.

After this I copied `conf/server/biostar.nginx.conf` into `/etc/nginx/sites-available/` with a symbolic link on `sites-enabled` pointing to the conf file on `sites-available`.

After started nginx, either `localhost/`, `localhost/robots.txt` or `localhost/sitemap.xml` returns small HTML with 404 Not found.

I have looked into the .conf file and I suspect that I need to change the URLs or some IP?

If you could lend some help on this, I would be very thankful. :smile:

**Comment by ialbert** [comment]
yes the documents are somewhat lacking because explaning deployment is a little outside of the scope of the project and it would make for a fairly lenghty document

The files that are provided  need to be edited slightly to point to the correct configurations and need to be thought of only as a starting point. I would recommend looking at the gunicorn deployment and/or nginx frontend for django in general and do some websearches on this. There are many blog posts that explain the concepts in great detail.

Typically the setup-by-step process is the following:

* Ensure that biostar works on a host and port and is able to serve Biostar (test directly on that port)
* Ensure that you can run celery worker from the command line
* Ensure that gunicorn works and can launch the same site as in point 1 when run from command line
* Stop gunicorn
* Ensure nginx works
* Ensure nginx can read the static document folder: /static/
* Ensure that nginx is set up to  proxy to a socket or port (when it does it will return a 500 bad gateway error, that is good ;-))
* Ensure that when guncorn is lanuched the site above works
* Create the supervisord init scripts that lanuch the gunicorn server
* Create the supervisord scripts that lanuch the celery tasks
* now set up elastic search

**Comment by poliveira89** [comment]
@ialbert Thank you for you reply :smiley: 

A more detailed questions/verifications if you allow me.

    1. The usage of Redis is to support Celery?
    2. Redis, can or should be used as Cache, as well?

**Comment by ialbert** [comment]
I will say that modern web deployment offers too many options and we have the paradox of choice. Redis can be used as both cache and message broker.  But that is a Celery feature really.

FWIW we use memchached for caching - it is very simple to set up.

**Comment by poliveira89** [comment]
Got it! :+1: 

Redis :arrow_forward: Celery
memcached :arrow_forward: Cache

If you allow me change the "subject", I'm struggling with Elastic Search.

This is a nice article to install it and test it: https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-on-an-ubuntu-vps

But now I'm stuck on configuration or index initialization.
For example, I'm looking into `conf/elasticsearch.json` and I don't know if I copy-past into Django settings or send it with HTTP request using Elastic Search REST API. As suggested on the following articles:

Article Nº1 -  http://www.wellfireinteractive.com/blog/custom-haystack-elasticsearch-backend/
In the first sub-section suggest to define DEFAULT_SETTINGS, like this:
````Python
DEFAULT_SETTINGS = {
    'settings': {
        "analysis": {
            "analyzer": {
                "ngram_analyzer": {
                    "type": "custom",
                    "tokenizer": "lowercase",
                    "filter": ["haystack_ngram"]
                },
                "edgengram_analyzer": {
                    "type": "custom",
                    "tokenizer": "lowercase",
                    "filter": ["haystack_edgengram"]
                }
            },
            "tokenizer": {
                "haystack_ngram_tokenizer": {
                    "type": "nGram",
                    "min_gram": 3,
                    "max_gram": 15,
                },
                "haystack_edgengram_tokenizer": {
                    "type": "edgeNGram",
                    "min_gram": 2,
                    "max_gram": 15,
                    "side": "front"
                }
            },
            "filter": {
                "haystack_ngram": {
                    "type": "nGram",
                    "min_gram": 3,
                    "max_gram": 15
                },
                "haystack_edgengram": {
                    "type": "edgeNGram",
                    "min_gram": 2,
                    "max_gram": 15
                }
            }
        }
    }
}
````
I suppose that the previous `DEFAULT_SETTINGS` are being defined on Django Settings file.

But forwarding on the article, last subsection, this appears:

````Python
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'myapp.backends.ConfigurableElasticSearchEngine',
        'URL': env_var('HAYSTACK_URL', 'http://127.0.0.1:9200/'),
        'INDEX_NAME': 'haystack',
    },
}
ELASTICSEARCH_INDEX_SETTINGS = {
    # index settings
}
ELASTICSEARCH_DEFAULT_ANALYZER = "snowball"
````
Which makes me a bit confused about where to put index information/settings.

Article Nº2 - http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-create-index.html

On this one, apparently I must create index through REST API of Elastic Search, like this:
````bash
$ curl -XPUT 'http://localhost:9200/twitter/' -d '{
    "settings" : {
        "index" : {
            "number_of_shards" : 3,
            "number_of_replicas" : 2
        }
    }
}'
````

Which method do you advise to use?
I appreciate all you help you gave until this moment! :smile:

**Comment by ialbert** [comment]
Our search is not customized in any way because I did not have time to investigate and understand the options and what they do. For the new release I plan the learn more about these. In the meantime I suggest not to worry too much about that - the search works well on default settings as well.

**Comment by poliveira89** [comment]
I know I read it somewhere, but now I cannot find it. How can I make WHOOSH_INDEX to index from time to time... or after every post?

Celery Job maybe?

Once again, thank you :+1:

**Comment by ialbert** [comment]
You need to run celerybeat - the default celery beat configuration is located at:

https://github.com/ialbert/biostar-central/blob/master/biostar/celeryconfig.py

it shows all the commands that will scheduled to run periodically when you run the beat. You still need to run workers as the beat only does the scheduling. See also:

http://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html
