### ISSUE TITLE
Unable to login to demo site

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#315]
Dear All

I have installed the application on an Ubuntu VM running in virtualbox on a Mac.  I followed the "Quick start" instructions:

> $ pip install --upgrade -r conf/requirements/base.txt
> $ source conf/defaults.env
> $ ./biostar.sh init import index run

I can run the site.  I can browse the site in a browser and everything seems in place (topics, user homepages, etc.).

However, if I try to login to the site ("email login") or to the /admin site I get a django error page with the error (e.g. for the /admin/ page):

> OperationalError at /admin/
> no such table: account_emailaddress

The database has clearly been created because the site content is there.  Have I missed something in the config? 

Any help much appreciated.

With thanks and best wishes

Ivan

**Comment by ialbert** [comment]
The problem is with django-allauth, you need to donwgrade to `django-allauth <=0.18.0`

see

https://github.com/ialbert/biostar-central/commit/7f998180eabd042349199bb861adb5536136ec70

and also:

https://github.com/pennersr/django-allauth/issues/819

https://github.com/pennersr/django-allauth/issues/804#issuecomment-72413162

**Comment by ialbert** [comment]
the other solution is to generate them like so before the migrations (we can't add this to the scripts as it is a workaround for a temporary problem):

    python manage.py schemamigration allauth.account --initial

**Comment by llaisdy** [comment]
Oh excellent!  Thanks very much!  I've downgraded django-allauth to 0.18.0, redone init & import, and there's no error.

Best wishes

Ivan
