### ISSUE TITLE
Badge error

### ISSUE THREAD

**Issue by tvvocold** [ialbert/biostar-central#317]
i had build  a community site using biostar, but cannot see the badge after somebody achieve something like "created more than 1,000 posts".
Why and how to fix?(or how to do a Badge test?)

**Comment by ialbert** [comment]
Are you running celery workers? Badges are awarded via asynchronous jobs. When a user logs in the create_user_award task is scheduled

https://github.com/ialbert/biostar-central/blob/master/biostar/awards.py#L53

this in turn runs the award definition as specified here

https://github.com/ialbert/biostar-central/blob/master/biostar/apps/badges/award_defs.py

**Comment by tvvocold** [comment]
do u mean i should run $conf/server/celery.worker.sh ?

**Comment by ialbert** [comment]
You need to understand how celery workers operate don't just run scripts

http://celery.readthedocs.org/en/latest/userguide/workers.html
