### ISSUE TITLE
deploy on webserver

### ISSUE THREAD

**Issue by vittel1** [ialbert/biostar-central#318]
The documentation of Biostar Central says:

"Example files can be found in the live/deploy folder."

But the folder doesnt exists?! Now I am not knowing what i have to write in the settings.

And is it possible to deploy it with an apache?

**Comment by ialbert** [comment]
Sorry about that I have now fixed both the docs and added the files. Here is the guide to deploy Django:

https://docs.djangoproject.com/en/1.7/howto/deployment/wsgi/

We use Gunicorn and deploy through Ngnix but  Apache/mod_wsgi should work as well - it will use more memory.

**Comment by ialbert** [comment]
Fixed in https://github.com/ialbert/biostar-central/commit/312a4c5273bba0830132a6a9090a7a1fdce91fac

**Comment by vittel1** [comment]
Thanks for the answer!

Can I find a virtualhost.conf for Apache somewhere? Or do i have to do it on my own?

**Comment by ialbert** [comment]
Virtual hosts straightforward to do in Apache: http://httpd.apache.org/docs/2.2/vhosts/examples.html
