### ISSUE TITLE
CSS libraries are fetched from internet

### ISSUE THREAD

**Issue by iCHAIT** [ialbert/biostar-central#325]
I actually have a query here, yesterday while I was working on my local developement server, my net connection went off and I realized that there are a few css libraries that are fetched from the internet and without those libraries the UI looks crappy.

So I was wondering if we could do something about it?

**Comment by llaisdy** [comment]
I have edited starbase.html to use relative (i.e., local) urls for css 
(part of IE8 coping strategy), and store the files in static/lib/.  You 
could do that.

Ivan


On 26/02/2015 10:44, Chaitanya Gupta wrote:
>
> I actually have a query here, yesterday while I was working on my 
> local developement server, my net connection went off and I realized 
> that there are a few css libraries that are fetched from the internet 
> and without those libraries the UI looks crappy.
>
> So I was wondering if we could do something about it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ialbert/biostar-central/issues/325>.
>

-- 
============================================================
Ivan A. Uemlianin PhD
Llaisdy
Speech Technology Research and Development

                     ivan@llaisdy.com
                         @llaisdy
                          llaisdy.wordpress.com
               github.com/llaisdy
                      www.linkedin.com/in/ivanuemlianin

                         festina lente
============================================================

**Comment by ialbert** [comment]
Yes perhaps we should have the defaults from local files and add CDN based location on deployed sites.

As Ivan says you can edit the starbase.html and replace the css with local paths.
