### ISSUE TITLE
Google Summer of Code - application guidelines

### ISSUE THREAD

**Issue by ialbert** [ialbert/biostar-central#328]
This year's Google Summer of Code students may propose work to improve Biostars via the INCF, The International Neuroinformatics Coordinating Facility.

https://www.incf.org/gsoc/2015/proposals

Applications to work on Biostars should aim to propose simple and well defined deliverables targeting on or more of the following:

1. Improving **system installation and deployment**: standalone executables (with py2exe, py2app), automated deployments via heroku or linode
2. Improving content search and **content federation**: connect different Biostar instances and allow them to search content across deployments
3. Better **email integration**: allow biostar to read existing email lists and be used in parallel to an email list
4. **Skinning and customizations** - refactor styling and display to  allow site owners to easily customize their site.

As an example last year's GSoC project delivered a REST API to interact with the site that has been an well received feature.

In addition qualified applicants may also propose to develop more advanced features such as data sharing via BitTorrent and/or WebTorrent protocols.

**Comment by Lohit13** [comment]
Hi
Under improving system installation, using py2exe or py2app, suggests that the app's executable will run on a windows or a mac. So it is to be run on the local server (localhost) right? If yes, should it run on the django's light server or is some other web server (for ex-apache) to be preferred?
Thanks

**Comment by ialbert** [comment]
I believe that everything could be done in pure python. Webservers like waitress or paster that could be used.

**Comment by narayanaditya95** [comment]
Hi @ialbert ,

I am a sophomore currently pursuing my Bachelors at IIT Kharagpur.
I want to express my interest in working on this project. I have prior experience in Django.

I hope this is the right place to talk about the project deliverables.
- ```Improving system installation and deployment:``` Can you explain in greater detail how would making executables help in automated deploys. I have worked on Heroku and never stumbled upon a use case where executable could be used.

**Comment by ialbert** [comment]
The use case is someone running the entire system off a laptop. Everything in Biostar can be deployed via pure python there are reasonably high performance webservers in python as well. 

The idea is to have a single simple app that one double clicks and the system starts up and can serve a  site with reasonable performance - can serve say dozens of simultaneous users.

**Comment by iCHAIT** [comment]
@ialbert could you please elaborate `Improving content search and content federation`
What different Biostar instances are we talking about here?

**Comment by ialbert** [comment]
An instance of Biostar may be set up to communicate with one or more other instances. Basically a simple REST api sendss metadata from one site to all others it is registered with. Then when users searches content on a site the search results results may show relevant content from the other sites.

Also a clarification - most of the features listed above would not need to be implemented from ground up by a candidate. All these features exist (or will exist) by the time the the GoSC starts. What the candidate needs to do is take them from a potentially rough and unpolished format to a well performing, documented and usable implementation (if that is needed).

**Comment by pattu777** [comment]
@ialbert I have cloned and set up the environment in my local system and went through the installation steps. Everything worked fine and the site is up. Now I am looking into what you said about "Improving system installation and deployment" thing. Currently you are using a shell script to install the app and using built-in Django server to run the site. 

So the use cases are deploying the app in 
1. Cloud Servers(AWS, Rackspace, DigitalOcean, Linode, GCE etc.)
2. Local Systems(Linux or Windows)
3. Any PaaS providers(Heroku, App Engine, Openshift etc.).

An alternative could be using setuptools and then py2app or py2exe to create an executable. But I guess a configuration management system(Chef, Puppet or Ansible) would be better.

Please clear me if I am wrong.

**Comment by ialbert** [comment]
yes there a few targets with different goals

1. Generic deploy scripts via Ansible that bootstraps the system on any supported Linux installation (this is for power users). 
2. bootstrapping onto an django application hosting service like heroku 
3. Executable on windows/max - minimal sys admin skills, just click and run.

for me 1 and 3 are most interesting since these will be used very soon and cover most use cases. heavy loads vs light loads.

**Comment by pattu777** [comment]
You have mentioned before that most of the features exist (or will exist) by the time the the GoSC starts. But I couldn't find any code for generic deployment. So If I plan on using Ansible for deployment, do I need to implement it from scratch?

**Comment by ialbert** [comment]
that refers to the candidate not having to make major design decisions on how the site is implemented - 

an Ansible script is very different, that being said we have fabric scripts  and shell scripts that could/should move to an ansbile

https://github.com/ialbert/biostar-central/tree/master/conf/fabs

**Comment by brainstorm** [comment]
Well, also from previous year's student, there's this ansible role that could use some care:

https://github.com/nimiq/ansible-biostar

@nimiq

**Comment by pattu777** [comment]
Thank you for the link. It seems deployment for AWS has already been implemented. Can you please mention which other cloud providers do you want to be supported?

Also can you please briefly explain the email integration thing.

**Comment by iCHAIT** [comment]
@ialbert How many different Biostar instances will we have to deal with at a particular moment of time or I should say how would we determine that how many instances of Biostar are active at a particular time?
Secondly how will we connect these different Biostar instances?What's the mechanism?

Also could you please explain email integration in detail?

**Comment by ialbert** [comment]
Well the minimum is two ;-)

The way I imagined it to work is that say instance owner Alice wants to share content with instance owner Bob and instance owner Bob agrees to that then the following happens:

1. instance owner Bob generates and gives instance owner Alice a specific secret key (password) that only relates to Alice.
2. instance owner Alice adds Bob's callback url and password their settings.
3. instance owner Bob adds the same secret key their settings.

Now every time a new post arrives to  Alice's system will also call out to Bob's instance and tell it information about the post, title, content. This content makes it into the search index on Bob's site. When people search for information at Bob's site they can see results from Alice as well. When they click a search result they are taken to Alice's site.

Important notes:

1. it is not symmetrical, Alice sharing with Bob does not mean Bob is sharing with Alice. To do the latter they need do the same steps the other way.
2. one site may exchange with many others and receive content from many others
3. As I mentioned before the core components for these features all exists - (or will exists) - what the project is about is to take it from mere existence to a practical useful, easy to manage, easy to set up and usable feature etc.

**Comment by iCHAIT** [comment]
Okay Great.
And what about Email integration?

**Comment by ialbert** [comment]
Email integration is about allowing a larger range of operation to be performed via email and doing so in a  way that is managable, rate limited, and won't be overrun by spam.

Allow new posts to be started, use the site as a mailing list, import existing mailing list with ease and run the site in parallel to a mailing list rather than having it be a replacement for it.

**Comment by Lohit13** [comment]
@ialbert Under Ease of Deployment, would you rather prefer a VM based configuration or using a container such as Docker? 
Ansible works quite well with both options. Though docker would allow us to set up multiple instances on a single host server (which I think leads to easier deployment), it has its downsides such as sharing the same amount of resources. So scalability would be a major deciding factor.

**Comment by ialbert** [comment]
Ease of deployment needs to be framed from the point of view of the user and not from the point of view of technology. The technology is the means to get there but not the goal. 

It is best to think in terms of a few user scenarios:

1. Life scientist wants to run the site on her laptop -> how many steps would she need to get a site running?

2. A conference organizer has a budget of $200 and wants to set up Biostar for conference --> can she do it in 20 minutes just by clicking on the web (for example a link like "host this site Heroku")

3. There is a two week summer course for programming, they know how to use Amazon EC2.  Can they also launch  Biostar from an AMI to support the course? 
...

X. Expert system admin using their own hardware is asked to deploy the site, what do they need to do?
