### ISSUE TITLE
"BAM" string gets auto-linked inappropriately

### ISSUE THREAD

**Issue by chrisamiller** [ialbert/biostar-central#330]
See: https://www.biostars.org/p/95700/#95708

I'm not a fan of this feature in general, but it's even worse when it links the word bam in the name of a tool (bam-readcount). Seems pretty confusing to talk about a software package and have a link created that doesn't go to the package's page.

Maybe you could at least beef up that regex to exclude instances where bam is pre- or succeeded by a hypen or slash? Thanks

**Comment by ialbert** [comment]
The software name autolinking is gone from next version of Biostar. 

As you point it out it may be error prone and it may also be too confusing in many instances - then it is too much work to get it work correctly and requires cherrypicking which packages get special treatment. 

In a few weeks time the new version will be deployed.

**Comment by chrisamiller** [comment]
Glad to hear it - thanks, Istvan!
