### ISSUE TITLE
Celery and Cron

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#333]
Dear All

For low traffic deployments the documentation recommends cron for asynchronous tasks and Celery in high traffic deployments [1].

If I understand biostars/celeryconfig.py [2] correctly, Celery is being used in the same way as cron would be --- e.g., running update_index every 15 minutes.

Is that correct?

The deployment I am working on it might be preferable to use cron and avoid having to use celery at all.

[1] http://docs.biostars.org/en/latest/deploy.html
[2] https://github.com/ialbert/biostar-central/blob/master/biostar/celeryconfig.py

With thanks and best wishes

Ivan

**Comment by ialbert** [comment]
the documentation could be a little clearer on that. The jobs in the celery
beat  schedule may be replaced with cron, see the CELERYBEAT_SCHEDULE below

https://github.com/ialbert/biostar-central/blob/master/biostar/celeryconfig.py

there are other tasks that need celery to run those decorated with
@app.task

in https://github.com/ialbert/biostar-central/blob/master/biostar/awards.py

these are triggered when a user logs in. These will only run via celery
worker.

Note that you may not need to set up a separate broker like rabbit MQ or
others. You can use the builtin broker that comes with django_celery
(kombu.transport, see celery docs) it should work fine as long as there
aren't too many parallel requests.


On 19 March 2015 at 08:13, Ivan Uemlianin <notifications@github.com> wrote:

> Dear All
>
> For low traffic deployments the documentation recommends cron for
> asynchronous tasks and Celery in high traffic deployments [1].
>
> If I understand biostars/celeryconfig.py [2] correctly, Celery is being
> used in the same way as cron would be --- e.g., running update_index every
> 15 minutes.
>
> Is that correct?
>
> The deployment I am working on it might be preferable to use cron and
> avoid having to use celery at all.
>
> [1] http://docs.biostars.org/en/latest/deploy.html
> [2]
> https://github.com/ialbert/biostar-central/blob/master/biostar/celeryconfig.py
>
> With thanks and best wishes
>
> Ivan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ialbert/biostar-central/issues/333>.
>



-- 
Istvan Albert
Associate Professor, Bioinformatics
Pennsylvania State University
http://www.personal.psu.edu/iua1/

**Comment by llaisdy** [comment]
Thanks. I was going to ask about updating user awards - I could only find user_crawl.

**Comment by llaisdy** [comment]
Thanks again - I've got celery working with rabbitmq.

User badges are updated when the user logs in, is that correct?  So if a user stays logged in all day, their badges won't be updated?

Ivan

p.s. thanks very much for making biostars available!

**Comment by ialbert** [comment]
no it gets triggered at every settings.SESSION_UPDATE_SECONDS interval when
the rest of the data is recomputed

https://github.com/ialbert/biostar-central/blob/master/biostar/server/middleware.py#L186

**Comment by llaisdy** [comment]
Ok, thanks.  I think that's all of my celery questions :)
