### ISSUE TITLE
Markdown in 3.0 incomplete parsing

### ISSUE THREAD

**Issue by mdshw5** [ialbert/biostar-central#334]
It looks like markdown parsing is not complete: http://test.biostars.org/p/108/#123

Underscores seem to be the only thing that's broken though!

**Comment by ialbert** [comment]
Great idea to test it with this. I will it add it  to the tests.

Ignoring underscores was done deliberately, there are many legitimate uses of underscores and double underscores inside words that can lead to undesired outputs. See the "code_friendly" option here:

https://github.com/trentm/python-markdown2/wiki/Extras

Another neat feature (missing from the original markdown spec) is the 'fenced codeblock'. Github also does that, enclosing text with three backticks  will turn that into code. This is much easier than indenting by four spaces. This latter can be impracticat.

**Comment by mdshw5** [comment]
The current behavior is fine with me, and _is_ probably less confusing for markdown newcomers. 

Matt Shirley

**Comment by ialbert** [comment]
This has been addressed just github did not close the issue.
