### ISSUE TITLE
Embedded YouTube video when ID contains a dash

### ISSUE THREAD

**Issue by nowlanfreese** [ialbert/biostar-central#335]
I noticed that I cannot embed a YouTube video that has a dash in the URL. 

For example, this video posted correctly: https://www.youtube.com/watch?v=HqnQKgJd254&feature=youtu.be (see Biostars post https://www.biostars.org/p/126760/)

While this video will not embed correctly: https://www.youtube.com/watch?v=Hs-iNCGa1CA (see Biostars https://www.biostars.org/p/134862/)

**Comment by ialbert** [comment]
This has been addressed.
