### ISSUE TITLE
Django 1.7 and biostar.apps.messages vs django.contrib.messages

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#338]
Dear All

Noting that biostar3 uses Django 1.7, I am upgrading to Django 1.7 to avoid South when changing some models.

Biostar uses two apps called "messages": biostar.apps.messages and django.contrib.messages.  As far as I can tell, Django 1.7 does not allow this.

Biostar3 has a completely different arrangement and I can't see how or even if it uses either of these messages apps.

Is there a correct and unobtrusive way to get around this, or do I have to rename biostar.apps.messages?

Thanks

Ivan

**Comment by llaisdy** [comment]
I've followed this post, which seems to do the trick:

http://stackoverflow.com/questions/24319558/how-to-resolve-django-core-exceptions-improperlyconfigured-application-labels

Now I'm getting "django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.", so I'm following this:

http://stackoverflow.com/questions/25680803/django-1-7-upgrade-error-appregistrynotready-models-arent-loaded-yet

Was the biostar upgrade to Django 1.7 like this?

Thanks

Ivan

**Comment by llaisdy** [comment]
Well I seem to have upgraded to Django 1.7.  Involved creating apps.py files and adding content to __init__.py to messages and users apps.  Did you avoid that somehow?

**Comment by ialbert** [comment]
I have done that too for Biostar 3.0

there is no reason to try to work around it.
