### ISSUE TITLE
Preview of a post with a long line in the first few lines spills over

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#339]
When a new post is created, with copy-pasted text that exceeds the width of the principal post `<div>`, it shows up alright with a scrollbar in the window. But on the messages page, where a preview of the post is displayed, the text is in a `<div>` where no word wrap happens.

This skews the display, as shows in this screenshot:
![screen shot 2015-04-17 at 12 38 12 pm](https://cloud.githubusercontent.com/assets/4529399/7206470/c367df20-e4ff-11e4-85fc-0d5b594faa05.png)

I tried messing with the HTML, and adding a `style="word-wrap: break-word"` to the `<div>` does it, but it probably needs to be added as a separate div class to the CSS and the `<div>`s on the Messages page be given this class.

**Comment by RamRS** [comment]
Maybe add a 
`.wrapped { word-wrap: break-word; }`
to
`biostar-central/biostar/static/biostar.base.less`

and change 
`<div class="stripe unread {{ message.unread }}">` 
to 
`<div class="wrapped stripe unread {{ message.unread }}">` 
in `biostar-central/biostar/server/templates/message_list.html` ?

**Comment by ialbert** [comment]
yes good catch - I may not fix it for the current site - will see how much time I have - but I will add it to the new site that I am planning to replace it with soon

**Comment by RamRS** [comment]
New site? BioStar 3.0? Sounds exciting. Any chance we could add automatic+manually triggered geo-tagging when User profiles are created?

**Comment by ialbert** [comment]
yes the demo site for 3.0 is at test.biostars.org

can you expand on what the geotagging means in this context

**Comment by RamRS** [comment]
I thought I'd explain it better in a new post, but here goes: I often see users registered with a false location. I think if we were to use browser capabilities to find location for the user, it'd be better. We could also offer an option to update location if they move, and if the browser is unable to determine location, then they could enter it manually.

**Comment by ialbert** [comment]
Well good news this already partly works that way. The site attempts to set the location automatically via a IP geo-lookup if it sees that settings as being empty.

But at any time a user has the option the change and override it as they see fit. (They can't really override it to empty because that will just be then set again). But they can set it to any non-empty value.

Always forcing a "correct" geo location feels a bit too intrusive as it may disclose private information that a user may not want to share.

**Comment by RamRS** [comment]
That makes sense. I did not think about privacy. I guess you've done the right thing and taken into account all concerns. Thank you for explaining this to me.

**Comment by ialbert** [comment]
This issue got a bit derailed and I forgot about the original suggestions. The CSS suggested by @RamRS has been now added.
