### ISSUE TITLE
What's ialbert password ? 

### ISSUE THREAD

**Issue by Sshuichi** [ialbert/biostar-central#342]
.gz | psql biostar3-main -U ialbert
gzip: init/biostar2/biostar2-postgres.sql.gz: No such file or directory
Password for user ialbert:

**Comment by ialbert** [comment]
this is used in my own development only and loads up the current biostar datadump to test out that the migration from 2 to 3 performs correctly. It won't be present in the release and it is only useful of one actually has a full datadump of a 2.0 site.
