### ISSUE TITLE
File and image upload

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#344]
Dear All

I'm about to add file upload to the post editor.  I notice you have this function on your list for Biostars3.  Have you made any progress?

As Biostars already uses ckeditor, I was going to try django-ckeditor.  Are you happy with ckeditor, or are you thinking of moving to something else?

Thanks

Ivan

**Comment by ialbert** [comment]
yes file uploads have been implemented for 3.0 - the editor will be swappable in 3.0 (it renders the content from a separate template) thus people may override it with a different one. The default editor will be Markdown based like StackExchange.

**Comment by llaisdy** [comment]
Where is the code for that?  I haven't been able to find it.

Thanks

Ivan

**Comment by ialbert** [comment]
the model has the file upload field, adding the file upload itself is just
a formality

https://github.com/ialbert/biostar-central/blob/3.0/biostar3/forum/models.py#L407

**Comment by llaisdy** [comment]
Thanks.  Is Biostar3 usable?  Is there a demo site running?

Ivan

**Comment by ialbert** [comment]
we have a demo site at:

http://test.biostars.org/

not all features have been turned on yet.

**Comment by llaisdy** [comment]
Nice site, thanks.  I see file upload hasn't been turned on yet.

**Comment by EvanChanSLA** [comment]
Is there a test account I can test drive this. username and password for this test site?

**Comment by ialbert** [comment]
@EvanChanSLA you can just go ahead and select the sign in option
@llaisdy this will be added very shortly, perhaps today

**Comment by llaisdy** [comment]
Cool!  Thanks.

**Comment by ialbert** [comment]
All posts now can have a file attached.

http://test.biostars.org/p/141/#146

**Comment by ialbert** [comment]
added in f3fd98a055f4099ab7bc07e619ee1d52cd307993
