### ISSUE TITLE
User Experience enhancements 

### ISSUE THREAD

**Issue by Sshuichi** [ialbert/biostar-central#346]
Hello.
I must say Biostars is very condensed. At the first sight, I get confused. 
Why don't we remove all the headers with their numbers and put them in a drop down list and put the numbers as badges like Bootstrap's way : 
http://getbootstrap.com/components/#badges

Also, can we switch ultimately to bootstrap ?

**Comment by ialbert** [comment]
Are you referring to Biostar 3.0? That has been already simplified (or so I hope)

http://test.biostars.org/

**Comment by Sshuichi** [comment]
Oh ! That's really much better ! I'll pull this to see it on my dev server  :)

**Comment by ialbert** [comment]
The interface will be redesigned and the UI features needs to be revisited then in the larger context.

But we definitely want  less stuff on the screen.
