### ISSUE TITLE
Secure/Build star

### ISSUE THREAD

**Issue by tvvocold** [ialbert/biostar-central#347]
ialbert,
U can use vaddy for secure testing.
(http://vaddy.net - Continuous web security testing with continuous integration (CI) tools. 3 domains, 10 scan history for free)

**Comment by tvvocold** [comment]
I got an interesting idea you may like:
How about build stars in biostar' homepage? (Something like https://github.com/danielmahal/Rumpetroll
or https://github.com/walkor/workerman-todpole, The homepage is  the universe .One group, One star)

**Comment by ialbert** [comment]
We are in issue cleanup mode, we'll close issues that are not strictly software related.
