### ISSUE TITLE
Exclude sections from search engines indexing

### ISSUE THREAD

**Issue by hmontenegro** [ialbert/biostar-central#352]
Is there a way of excluding "similar posts", "recent votes", "recent replies", etc, from search engines indexing? It may lead to spurious hits, leading to posts unrelated to the original search.

**Comment by ialbert** [comment]
Google advises to to mark the selectors on Webmaster Tools. You can set a parameter name to represent a sort or limiting operator and the google bot will understand that.

But yes the point is valid, it is very annoying to have bots crawl various sorted pages and try all combinations.

**Comment by ialbert** [comment]
I will close this since there is no other answer than that stated above.
