### ISSUE TITLE
Moderation action to move an answer to a comment on the first/accepted answer

### ISSUE THREAD

**Issue by lawremi** [ialbert/biostar-central#353]
Often users will reply to an answer by leaving a new answer. It would be nice to be able to fix that by moving the answer to a comment on the accepted answer, or to the first answer, if none has been accepted.

**Comment by martenson** [comment]
Or to move it to any answer/comment. However UI for this feature is not a trivial job.

**Comment by ialbert** [comment]
this functionality exists in 3.0 - one of the moderation options is called re-parent and has textbox associated with it. Into this textbox  one can enter a post id and it will move the moderated post as a child of that post. The new parent has to be in the same thread as the old parent.

**Comment by martenson** [comment]
@ialbert awesome! thank you

**Comment by Natay** [comment]
This has been fixed in the most current version of Biostar, we have a drag and drop option as well that allows users to reparent using a simple UI.
