### ISSUE TITLE
improvement to the 'Accept' feature

### ISSUE THREAD

**Issue by martenson** [ialbert/biostar-central#355]
Big chunk of people asking questions do not accept any given answers even if they are correct because they do not notice the 'Accept tick'. I assume that the reason is partially because it does not look like a button/active element.

Combined with moderators not having an option to accept answers for them this troubles us at https://biostar.usegalaxy.org and we would really welcome an improvement in this.

**Comment by ialbert** [comment]
I can add the accept as a moderation action. We'll see how it gets used.

**Comment by martenson** [comment]
great, thanks a bunch @ialbert !

**Comment by RamRS** [comment]
I was wondering why this feature was for. This clarifies it. Should be useful in a few cases at Biostars.
