### ISSUE TITLE
Improvement: add automagically a tag to a new post whenever launched from ^/t/TAG page 

### ISSUE THREAD

**Issue by yarikoptic** [ialbert/biostar-central#356]
some projects refer to their Q&A collections identified by tags (e.g. as on neurostars.org), but then invoking a New Post action from that project associated page creates just a generic new post without linking it to the project via tag.  So I thought it might be of benefit to have that tag added automagically.

**Comment by ialbert** [comment]
This can be done by filling in parameters in the New Post link:

/p/new/post/?tag_val=minia,assembly

You can also prefill title or even content (needs to be urlencoded):

/p/new/post/?tag_val=minia,assembly&title=Hello&content=World

**Comment by brettz9** [comment]
Is this still doable? Neither https://www.biostars.org/p/new/post/?tag_val=scaffolds or https://www.biostars.org/new/post/?tag_val=scaffolds seem to be working.

**Comment by ialbert** [comment]
this has not been implemented in the new version - we have completely forgotten that it even worked this way,

is this a used feature?

**Comment by brettz9** [comment]
Thanks for your reply. As a new user,I absolutely want to use it that way for our site, at least for tags. We have wikis and knowledge resources of various topics from which we'd like to be able to link to the forum such that a relevant tag or tags is already in place.

We can then also more meaningfully link from the resources to a tag search of the same name on the forum, knowing that previous posters would be using that tag. (And maybe a Biostar mod could in turn use the tags of the page to create links back to our resources.)

**Comment by ialbert** [comment]
@brettz9 this is not a difficult feature to add back, we'll add this back then @Natay

**Comment by Natay** [comment]
Okay, we will have this added

**Comment by Natay** [comment]
@brettz9 This has been added to the site

**Comment by ialbert** [comment]
The second form works

https://www.biostars.org/new/post/?tag_val=scaffolds

**Comment by brettz9** [comment]
Awesome, thank you so much! And thanks for your work on this impressive software... Very eager to try it out...
