### ISSUE TITLE
Cite button under each question (post).

### ISSUE THREAD

**Issue by sukhdeepsingh** [ialbert/biostar-central#378]
Hi,

I was thinking about having a button "cite" under each post (question) next to link,edit and moderate, clicking on which generates a bibtex citation for that respective post. I reckon it's not a lot or work and will motivate people to cite the single posts. The posts are the resource of information and would also attract more traffic when cited in thesis, papers etc.

Cheers
Sukhi

**Comment by ialbert** [comment]
I am cleaning up the issues to keep those I think have a good chance to make it in. Here the concern is that latex is not as widely used by those that write papers with bioinformatics related content. So at that point we should support different formats and that will add to the maintenatnce burden.
