### ISSUE TITLE
Questions/Help with setting up Biostar.

### ISSUE THREAD

**Issue by sbagmeijer** [ialbert/biostar-central#380]
Hello,

I am trying to move my website to this Biostar software as I like it very much so far, however I am stuck on a few things and I cannot really find the solution in the documentation, I was hoping someone could help me.

First of all the website in question is: http://test.ulyaoth.net 
It runs with a postgresql database.

This are my questions:
Problem 1: 
How exactly do you get the 3th party authentications to work for Facebook? I added all the keys to the ".env" file and it looks now like this:

*update*
Got Problem 1 solved, everything did go much smoother once I found out there is a /admin page, not sure how I missed that :).

Problem 2:
on the "New Post" forum how can I alter the options that "Post Type*" contains so I can make that fit how I edited the website?.

Problem 3:
How can tweak the settings for the email sign up right now whatever I try to sign up with it always gives the error: "Form based signup is now disabled because of spam."

Problem 4:
How do you remove the version numbering from the bottom so it only does say: "Powered by Biostar."

And as final is there a way to lock a certain board so for example in the top I created a link called "Repository" is there  a way so only the admin could post in here and people can only reply to those posts?

Thank you so much in advanced for any help and for the software!

**Comment by ialbert** [comment]
Note that we will move to version 3.0 (see branch 3.0) possibly this summer see  http://test.biostars.org/

But you can use 2.* versions as there will be a seamless upgrade path to 3.0.

The post types come from https://github.com/ialbert/biostar-central/blob/master/biostar/apps/posts/views.py#L57

The email based authentication was disabled (though that was not actually supposed to make it into the master), get rid of the clause True here (that will make the error trigger at all times):

https://github.com/ialbert/biostar-central/blob/master/biostar/apps/util/captcha/fields.py#L31

To remove the versions edit the page: https://github.com/ialbert/biostar-central/blob/master/biostar/server/templates/starbase.html#L145

Locking a banner is not yet possible but the new version has the concept of separate boards (subdomains) that can have that feature added.

**Comment by sbagmeijer** [comment]
Will there be much changed database wise from now on?

If I move to the 3.0 version now and just keep the code base up to date it should bring me eventually to the final release or would I still need to do converting?

**Comment by ialbert** [comment]
yes, we do not anticipate many changes in the database anymore everything is migrated anyhow so what you have would keep working seamlessly.

I would recommend using 3.0 as well.

**Comment by sbagmeijer** [comment]
Got it up and running, had some issues because it seems if I do "./biostar.sh run" that it will not load the "/static/" content.

But when i run it in waitress it seems to work fine: https://test.ulyaoth.net

Look good so far will test it little more :).

**Comment by ialbert** [comment]
it all depends on the DEBUG settings, when that is False the static content will not handled by the django server. it is a Django thing...

**Comment by sbagmeijer** [comment]
That explains I had it False indeed.

**Comment by sbagmeijer** [comment]
Alright thank you very much for all the help and pointing to the newer version I shall play around with it for next few days to see if I can move over my full website.

I will close the issue :+1:
