### ISSUE TITLE
Incorrect post linked for "Scholar" badge

### ISSUE THREAD

**Issue by ying-w** [ialbert/biostar-central#386]
Not sure how prevalent this is, just noticed this:

A recent post that I made was accepted as the right answer: https://www.biostars.org/p/152023/#152145
However, when I look under my [messages](https://www.biostars.org/local/messages/) , the notification links to a different post:
"Congratulations! You have won the Scholar badge for the notable accomplishment of: created an answer that has been accepted. You have earned this honor for: [A: How can I programmatically download the GEO DataSets of a given accession?](https://www.biostars.org/p/113070/#113220)"

I think the posts it linked to might have been the last post that I had an answer accepted for, not the most recent one, not too sure

**Comment by ialbert** [comment]
yes, this is a known bug, it reports the first post if there are more awards of the same type. Fixed in 3.0.

**Comment by ialbert** [comment]
This will be tracked via https://github.com/ialbert/biostar-central/issues/309
