### ISSUE TITLE
Tags Daily Digest 

### ISSUE THREAD

**Issue by braniti** [ialbert/biostar-central#391]
hi  developers ,

  Is it possible to add  Daily digest feature for all tags followed  ?  
This was important  feature of the old mailing lists (usually a summary of all daily massages) . 

Issue i have is that  because I  follow  about   10   tags i receive many comments and answers  every  day ...   This is jamming  my inbox   .

  I contacted https://support.bioconductor.org/p/72539/#72569 
to ask about this and Dan directed me here ... 

  All the best and thanx for developing this web application .

Branko.

**Comment by ialbert** [comment]
Yes this is a good suggestion and it would indeed be very useful.

We will add it to the important feature list.

**Comment by braniti** [comment]
great , thanx.   
 maybe also :
- allow option to give digest of   TOTAL forum  (not only tags) 
- allow  1 digest a day,  or 1 a week
