### ISSUE TITLE
Reissuing of awards

### ISSUE THREAD

**Issue by chrisamiller** [ialbert/biostar-central#398]
I keep seeing awards for the same posts pop up over and over again in my feed. It's pretty evident from looking at my user page:

```
Scholar  6 days ago, created an answer that has been accepted. 
For A: Spliting a dataframe based in a chromosome 

Scholar  8 days ago, created an answer that has been accepted. 
For A: Spliting a dataframe based in a chromosome 

Scholar  11 days ago, created an answer that has been accepted. 
For A: Spliting a dataframe based in a chromosome 

Scholar  12 days ago, created an answer that has been accepted. 
For A: Spliting a dataframe based in a chromosome 

...
```

Clearly something isn't right here.

**Comment by ialbert** [comment]
There is a bug there that reports the first of your award even when you earn a new one. You do have these many awards so that is good ;-)

**Comment by chrisamiller** [comment]
If this is a known issue, is there an existing bug report? If so, happy to close. If not, will leave this open.

**Comment by ialbert** [comment]
This is also noted in https://github.com/ialbert/biostar-central/issues/386 seems the same badge has this problem.

I will look into it next.
