### ISSUE TITLE
Use markdown for post editing

### ISSUE THREAD

**Issue by ialbert** [ialbert/biostar-central#399]
The current posting is done via CK Edit window and has turned out to be less than optimal. We are moving to a markdown based  editor.

**Comment by ialbert** [comment]
Follow this branch https://github.com/ialbert/biostar-central/tree/markdown

**Comment by ialbert** [comment]
Most work for switching to Markdown in cf8f4e1ed462bb9bd13ef074cea34b3f9972dcf7

**Comment by RamRS** [comment]
You're nailing this today?

--
Ram

**Comment by ialbert** [comment]
Hopefully it gets nailed :8ball:

**Comment by ialbert** [comment]
This has been implemented in e15b52cee7f80ae3705ed78199419b9001f1017e and subsequent changes in the markdown branch.
