### ISSUE TITLE
Biostar upgrade path

### ISSUE THREAD

**Issue by ialbert** [ialbert/biostar-central#400]
**Short recap**: there is an unreleased version of Biostar 3.0 and an almost ready version called Biostar 4.0. During the development of these releases we've realized that the software and the community around it became so large that it became extremely difficult to create fully functional full releases like 3.0 and 4.0. A lot of code is ready to go but not quite finished as a whole.

**The inability to replicate the full functionality of the site has been a major blocker of adding even simple features**.

We will give this is a shot in a different way. The site will be rewritten and the new code used as soon as it is ready, basically rewriting it one  chunk at a time while being deployed in the same system. Hence some parts of the site will run the old code and show the old templates and some parts will run the new code and show the new templates until the new fully replaces the old. The site will be kept production ready and functional at all times.

**Note:** there won't be releases such as **3.0** or **4.0**. Instead Biostar will release versions by calendar dates: for example if a release was made on 2016/02/27 it would be called **16.02**. All releases are to be fully compatible with the previous ones and will have automated migrations.

--- Edits ---

The branch called `production` will always be in sync with the code that runs the main server and will contain all production ready features from other branches. Currently the highest priority tasks are:
1.  Catch up to Django 1.9 (actually 1.10 as much as possible) see the `django19` branch. 
2.  Switch over to `python3.5`. 

All along we will continuously swap out one small section at a time.

**Comment by davidbau** [comment]
Istvan - a question.  I am considering using biostars as the basis for a new community site. Should I start by looking at the 4.0 fork or start with master?

**Comment by foreveremain** [comment]
+1 - I interpret the above as 'use most recent release and be ready to apply migration scripts regularly'

**Comment by ialbert** [comment]
yes, as @foreveremain said, migrations all the way ;-)

The branch called `production` will always be in sync with the code that runs the main server and will contain all production ready features from other branches. After a pull one should generally rerun the pip installer to update the dependencies.

`pip install  -f conf/requirements/base.txt `

Currently the most urgent task is to catch up to Django 1.9 (actually 1.10 as much as possible)  see the `django19` branch. Then the next priority will be to switch over to `python3.5`. All along we will continuously swap out one small section at a time.

**Comment by jaypatelani** [comment]
are we going to have google adsense integration too?

Thanks,

Jay

**Comment by ialbert** [comment]
The way this works is that there are small files called "leaderboard", "sidebar" etc that get included into each page. Currently these files are all empty.

When one customizes the site they can override these  by putting customized versions of them into a folder that comes first in the template path.

**Comment by jaypatelani** [comment]
Ohh okay. Thanks @ialbert

**Comment by jaypatelani** [comment]
Freature request : integration of system like https://mobbr.com possible? or useful to biostar community? 

Thanks.
