### ISSUE TITLE
Markdown preview doesn't match actual markdown on submit

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#401]
Fenced codeblocks are rendered differently in preview vs in actual. For example, the preview:
![Preview_Image][1]

becomes the actual content:
![Actual_Image][2]

  [1]: http://i.imgur.com/4QsheiK.png
  [2]: http://i.imgur.com/cDp7UDm.png

**Comment by ialbert** [comment]
The javascript visualizer that comes with the editor supports fewer Markdown options than what we actually can do with the content (it is not actually round tripping to the server). 

I am investigating other editors like this for example: https://simplemde.com/

But I will close this as the fenced code blocks are actually an extra feature that is beyond the Markdown spec and it is more of a convenience function. Still somewhat annoying that it does not show it right.
