### ISSUE TITLE
Expiry Date for Jobs

### ISSUE THREAD

**Issue by DarioS** [ialbert/biostar-central#403]
I think it would be convenient if those who were creating job advertisements could set an expiry date, after which the advertisement would automatically be deleted.

**Comment by ialbert** [comment]
In my opinion the job description should contain that information. 

I don't like the concept of automatically deleting job posts - there is a lot to be gained from perusing this later and looking how the job market evolved, who hired and what type of skills they wanted. Reading that also has quite a bit of educational value.

But you are right in that it would be nice to be able to mark the posts to show their "expiration" alas that is a user interface element that we would need not jut to implement but to train the users on how to make use of it.
