### ISSUE TITLE
deploy.env and deploy.py not found

### ISSUE THREAD

**Issue by kevinlee05** [ialbert/biostar-central#404]
The deployment docs say "We recommend that you start with the files in  live/deploy*  and copy them another name. The  deploy.env  and  deploy.py  files show the minimally necessary variables that need to be set."

However after executing all the instructions in the docs I can find neither deploy.env nor deploy.py in the live folder. what am I missing?

**Comment by ialbert** [comment]
Have been renamed to `staging.env` and `staging.py` will fix the docs.
