### ISSUE TITLE
"compress css" is not working

### ISSUE THREAD

**Issue by victorylin** [ialbert/biostar-central#408]
deploy the biostar by deloy.env with gunicorn and nginx , but the css compress is not working.

the web page source is here. 

            <link rel="stylesheet" type="text/css" href="/static/lib/prism/prism.css">
            <link href="/static/lib/select2-3.4.5/select2.css" rel="stylesheet">
            <link rel="stylesheet" type="text/less" href="/static/biostar.style.less">
            
            <script src="/static/lib/select2-3.4.5/select2.min.js" type="text/javascript"></script>
            <script src="/static/biostar.js" type="text/javascript"></script>

**Comment by ialbert** [comment]
The compression works via django compressor and needs a few settings to make it work:

specifically make sure the following two settings are set like so:

    DEBUG = False

and 

   USE_COMPRESSOR = True

**Comment by victorylin** [comment]
thank you for your corporation! the Settings seems no problem. maybe the web environment has some problems, i will continue  to check it.
