### ISSUE TITLE
my deployment shows biostar version 16.03 

### ISSUE THREAD

**Issue by jaypatelani** [ialbert/biostar-central#410]
Hi all,

1 .Is it normal that version at the end of website showing 16.03 ? www.bsdguru.in is my website.

2. For setting up email do we need to put EMAIL_BACKEND settings in base.py or in live folder with settings.py?

Warm Regards,
Jay

**Comment by ialbert** [comment]
yes the new versioning system goes by the release date, 16-03 is March 2016.

put the email settings and all private information into the settings file of the live folder.
