### ISSUE TITLE
using graphviz on biostar-central models

### ISSUE THREAD

**Issue by bicepjai** [ialbert/biostar-central#411]
have any one successfully generated [graphviz](http://graphviz.readthedocs.io/en/latest/manual.html) model graph on biostar-central app models ?

**Comment by alevchuk** [comment]
@bicepjai could I get more of the "why and how" for this? also, what is app models?

**Comment by alevchuk** [comment]
I'm assuming you want to be able to display graphs (nodes and edges) in posts. What is the specific story where you wanted to use this?

**Comment by bicepjai** [comment]
I am looking to understand the database models, so that i can extend it for my application. It might be easier to understand with model graph, hence iw as interested in viewing the graphical visualization of the biostar-central database model graph.

**Comment by alevchuktest** [comment]
There is a generic Django models visualization tool: https://code.djangoproject.com/wiki/DjangoGraphviz

Instructions to generate a visual (PNG file) are here: https://github.com/django-extensions/django-extensions/blob/master/docs/graph_models.rst

@bicepjai would you be interested in giving it a shot?

**Comment by alevchuk** [comment]
There is a generic Django models visualization tool: https://code.djangoproject.com/wiki/DjangoGraphviz

Instructions to generate a visual (PNG file) are here: https://github.com/django-extensions/django-extensions/blob/master/docs/graph_models.rst

@bicepjai would you be interested in giving it a shot?
