### ISSUE TITLE
Small formatting issue with urls and comments 

### ISSUE THREAD

**Issue by JohnLonginotto** [ialbert/biostar-central#413]
It seems like a valid URL followed by a newline and a "<" results in everything after the "<" being invisible -- but only when both url and "<" are in a code block.

For example:

```
http://google.com
<Everything after the "<" is hidden, including the "<" itself.
This will continue until the end of the code block if there is no closing square bracket.
```

**Comment by ialbert** [comment]
I am able to reproduce this, it is weird corner case that comes from the bleach library's linkify method.

https://github.com/mozilla/bleach

It manifests itself as:

```
import bleach

text = '''
http://foo.com
<bar
'''
html = bleach.linkify(text)

print text
print '---'
print html
```

We have already contributed back some patches to this library to fix certain behaviors discovered on Biostar:

https://github.com/ialbert/bleach

Hence this will need some investigation as well.

**Comment by Natay** [comment]
This issue has been fixed in the most current version of biostars.
