### ISSUE TITLE
emails not working.

### ISSUE THREAD

**Issue by jaypatelani** [ialbert/biostar-central#414]
Running Biostar version 16.03  and log shows no error in celery or other but emails are not working. Tried both Django and celery email settings. 
My settings.py
`#CELERY_ALWAYS_EAGER = True
EMAIL_USE_TLS = True
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'biostar.mailer.CeleryEmailBackend'
CELERY_EMAIL_BACKEND = 'biostar.mailer.SSLEmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER =
EMAIL_HOST_PASSWORD =`

as well Recent location and Recent Awards not working. Let me know if i need to check some specific settings.

Thanks
Jay

**Comment by ialbert** [comment]
You need to set it to the console output. If the console output shows the emails then the emails settings or the way celery is run are not correct. Awards and recent location are also set via celery tasks. 
I think the celery is not set up quite right.
