### ISSUE TITLE
Auto-added tags bypass tag size limit until post is edited

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#415]
This is from the user perspective - it looks like there is a 50 character limit on the Tag field for posts. I have noticed this while editing a few posts - after a content edit, when I click Update, I get an error on the tags being over the size limit in length. But the post was submitted with those tags.

The only reason I can think of this is that when adding the auto-added tag based on post type, the size limit is not checked. If this is the case, should the validation be extended or made more lenient? Or should it be bypassed on edit by the edit-er removing the post-type tag so it can be auto-added without triggering the validation error?

**Comment by Natay** [comment]
We no longer have auto-added tags to posts, users can set tags in new post forms using ?tag_val=tag but that gets validated the same way.
