### ISSUE TITLE
Support languages other than English in posts.

### ISSUE THREAD

**Issue by tnabtaf** [ialbert/biostar-central#416]
Feature request:

I'm trying to post an announcement to Galaxy-Biostar that contains Arabic text.  I can get the preview to work, but when I try to submit the post, it won't let me, telling me:

> Language "ar" is not one of the supported languages ['en']!

It does this even if I omit the lang attribute or lie and say it's "en".  I see the same behavior on the main BioStar site.

It would be great if BioStar supported other languages besides English.  I had to post this one without the Arabic text, which probably conveys the wrong message to the community we want to reach.

![biostarfullscreen](https://cloud.githubusercontent.com/assets/1622414/19776119/b60100a6-9c27-11e6-9d72-144ef0a626b6.png)

**Comment by ialbert** [comment]
The system does support other languages but these are turned off by default as a lot of spam used to come in that way and helps enforce a language (if that is desired). To expand languages the following settings needs to be changed:

https://github.com/ialbert/biostar-central/blob/master/biostar/settings/base.py#L177

I did that for your site and restarted your server. That should  fixed this problem.

**Comment by tnabtaf** [comment]
Dang, that was fast!

I've added the Arabic text to my post: https://biostar.usegalaxy.org/p/20343/

It looks good except it isn't right justified.  It is right justified in the preview.  I wrap that section in 
`<div dir="rtl" lang="ar" style="text-align: right">`

**Comment by ialbert** [comment]
There allowed HTML tags are whitelisted (and externally configurable) here:

https://github.com/ialbert/biostar-central/blob/master/biostar/settings/base.py#L158

I have added the changes that you need and if you edit and resave the post (no other thing needed) it should now work.

**Comment by tnabtaf** [comment]
Thanks Istvan.  

It's a thing of beauty.
