### ISSUE TITLE
Language checking: Language "x" is not one of the supported languages

### ISSUE THREAD

**Issue by llrs** [ialbert/biostar-central#424]
When I try to post a question in support.bioconductor.org, **sometimes** I receive the following message: 

> Language "ca" is not one of the supported languages ['en']!

I am using Mozilla Firefox 50.1.0 on a Linux distribution based on Ubuntu (Biolinux). The only reason why a "ca" might appear is because I have a Catalan dictionary installed in my browswer (but I am not using it when posting). How (and why) is the language checked for posting? It is an error of my browser configuration or of biostars posting scheme?

**Comment by ialbert** [comment]
This has been discussed here

https://github.com/Bioconductor/support.bioconductor.org/issues/33
