### ISSUE TITLE
RSS feeds not updating

### ISSUE THREAD

**Issue by mr-c** [ialbert/biostar-central#431]
Example: https://www.biostars.org/feeds/tag/cwl/ contains no posts from 2017

yet last post on that tag was from six days ago: https://www.biostars.org/t/cwl/ https://www.biostars.org/p/245091/

**Comment by mr-c** [comment]
Ping, this is still not working :-(

**Comment by artempronevskiy** [comment]
@mr-c you can propose code changes via pull request, maybe it will be faster...
