### ISSUE TITLE
"Watched tags" doesn't send notification

### ISSUE THREAD

**Issue by dariober** [ialbert/biostar-central#434]
As explained here https://www.biostars.org/p/258402/, the "Watched tags" option in the User's profile doesn't seem to work, i.e. no notification is sent when a post matching a tag appears. It would be great if it could be fixed as it would be really useful.

**Comment by ialbert** [comment]
yes, I will try to look into this since this been going on for a while.

**Comment by Natay** [comment]
This issue has been fixed
