### ISSUE TITLE
Is it possible to display this in other language?

### ISSUE THREAD

**Issue by harryyuanfeng** [ialbert/biostar-central#436]
For example, I want to use this to target Chinese customers? How can I make it so that it display Chinese?

**Comment by llaisdy** [comment]
It does already, doesn't it?

**Comment by ialbert** [comment]
Previous versions of Biostar had the feature of internationalization but that made the templates much more difficult to work with. As a matter of fact there was a chinese version of it.

https://github.com/ialbert/biostar-central/blob/biostar1/main/server/locale/zh_CH/LC_MESSAGES/django.po

alas the feature did not get use or much traction and only added difficulty to the code so it got dropped from the latest version.
