### ISSUE TITLE
Old jobs URL https://www.biostars.org/show/jobs/

### ISSUE THREAD

**Issue by peterjc** [ialbert/biostar-central#437]
Based on the ISCB page https://www.iscb.org/iscb-careers-job-database/other-bioinformatics-jobs-board the site used to show jobs via: https://www.biostars.org/show/jobs/

Could this be restored as a redirection to: https://www.biostars.org/t/jobs/ please?

I will separately email the ISCB to update https://www.iscb.org/iscb-careers-job-database/other-bioinformatics-jobs-board

**Comment by Natay** [comment]
The https://www.iscb.org/ site has updated to /t/jobs to match our url schema
