### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1f61ipqp/akismet/

### ISSUE THREAD

**Issue by harryyuanfeng** [ialbert/biostar-central#438]
when I run 

`pip install --upgrade -r conf/requirements/base.txt`

```
Collecting akismet==0.2.0 (from -r conf/requirements/base.txt (line 9))
  Using cached akismet-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1f61ipqp/akismet/setup.py", line 5, in <module>
        import akismet
      File "/tmp/pip-build-1f61ipqp/akismet/akismet.py", line 136
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1f61ipqp/akismet/

```

Python 2.7.9
pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)

**Comment by ialbert** [comment]
You will need to use Python 2.7 for this. See how the error comes from an akismet library so it is not even under our control.

It is true that time has come to update for Python 3.0 but that won't happen this year - perhaps next year,

**Comment by harryyuanfeng** [comment]
I updated my question with python version. @ialbert 

so what should I do exactly? downgrade my python?

**Comment by ialbert** [comment]
Downgrade is a strong word and it used to be that you had to get rid of one python to use the other. That is not neeed anymore.

I general use conda or other virtual environment manager where several versions of python can "coexist in peace"

for example:

    conda create --name py2 python=2
    source activate py2

now that particular shell runs python 2.
