### ISSUE TITLE
Bioconductor Support Site Customization directions ...

### ISSUE THREAD

**Issue by nmvega** [ialbert/biostar-central#441]
Hi again Friends:

I'm moving on now to try to customize my instance with a Look/Feel/Skin/Theme that is identical to the [bioconductor support site](https://support.bioconductor.org/).

To do that I implemented the Customize instructions [here](https://github.com/ialbert/biostar-central/blob/master/org/bioconductor/README.md), but I'm not having luck.

First, I should note that the following line in those instructions probably needs adjusting:
FROM: `TEMPLATE_DIRS = [THEME_PATH] + TEMPLATE_DIRS`
TO: `TEMPLATE_DIRS = [THEME_PATH,] + list(TEMPLATE_DIRS)`

Or, alternatively, TEMPLATE_DIRS in biostar.settings.base could be made into a List instead of a Tuple.

Anyway, I followed the page instructions:
- `cd /home/www/sites/biostar-central/org/bioconductor/`
- `rm -rf *`  # Remove three unneeded files in the above directory.
- `cp -rp ../../biostar/server/templates .` # This directory now has a `templates` directory, too.
- `cd ../../live/` # Back in the live directory we adjust the template search list order in `deploy.py`.
- `vi ./deploy.py` # And add these three lines ...
`import os`
`THEME_PATH = os.path.join(HOME_DIR, 'org', 'bioconductor', 'templates')`
`TEMPLATE_DIRS = [THEME_PATH,] + list(TEMPLATE_DIRS)`

Finally, I wasn't sure if I needed to rebuild the site from scratch (via `biostar.sh init`) with these changes, or if gunicorn only needed to be restarted. So I tried both (starting with just restarting gunicorn), but neither action resulted in things looking like the [bioconductor support site](https://support.bioconductor.org/) skin, theme and colors (etc).

It's possible that my understanding of templates versus themes/skin is misguided. If so, any step-by-steps to achieve the look/feel/theme/skin of the bioconductor site would be grand.

Thank you in advance!

**Comment by ialbert** [comment]
I believe that the bioconductor team has added more changes that are not present in the current template. To test that the site pulls from the new templates add some new content to them.

Depending on how the django templating is loading (and unless you have instructed it to cache the templates) you would not need to restart the server to see changes in templates.

**Comment by nmvega** [comment]
Ah, okay.

I will figure out the latter when I have template changes to apply. I really love this solution and want it to work (eventually contributing back is some way), but I'm in the "struggle with it" phase currently.

I don't know which Bioconductor admin, in particular, to contact about their template, but I guess I'll try one on the list ... Okay, maybe two. =:)

Thanks again!

**Comment by nmvega** [comment]
P.S. I never noticed this fork until a URL on the Bioconductor About page directed me there (just now):
https://github.com/Bioconductor/support.bioconductor.org

Question:
Would perhaps cloning a **branch** (TBD) of that variation (URL above) yield the template/theme I'm looking for? And, as importantly, does that variation (URL above) include the latest software updates/fixes (including, for example, the merge update made just yesterday)? I wouldn't want to go backwards. :)

**Comment by ialbert** [comment]
I am not currently working with that fork so I would not know.

**Comment by nmvega** [comment]
Thank you. I will post an issue-question on that fork.

**Comment by nmvega** [comment]
What is/are the differences between ...
- `version 16.09` which I see on my **production branch** installation --and--
- `version 2.3.0` which I see on the biostar.org (and `v2.2.0` on support.bioconductor.org) sites.

Thank you.

**Comment by ialbert** [comment]
At some point we switched to a year/month type of labeling of releases so 16.09 means: 2016, September. 

That release was done at the request of the Galaxy team, they needed a few additional moderation capabilities. Their site runs that codebase:

https://biostar.usegalaxy.org/

The changes were adding the ability to bump a post and what happens when a moderator edits a post whether the post gets bumped by this action or not.

I've not updated the main site as the changes were minor and some other work was planned - that in the end did not materialize.

**Comment by nmvega** [comment]
Ah, I understand now. And thank you for keeping this ticket open. (◠﹏◠) 

I'm sticking with your initial **biostar-central** build exclusively and customize that (if I customize much at all). I have the most confidence in this version now, plus when seeking ongoing professional support in the future (alluded to on the GitHub landing page), things will be easier (very familiar).

**Comment by nmvega** [comment]
Hello:

I was starting to adjust the Social Authentication methods in `live.deploy` as shown below using overrides (example). However should I instead be doing this **exclusively** in the Django Admin panel? Or some combination of both? I'm unsure. Thank you again.

`./live/deploy.py:`
```
INSTALLED_APPS.remove('allauth.socialaccount.providers.persona')  # Remove
INSTALLED_APPS.append('allauth.socialaccount.providers.google')   # Add
INSTALLED_APPS.append('allauth.socialaccount.providers.linkedin') # Add

_GOOGLE = {
  'SCOPE': ['email', 'https://www.googleapis.com/auth/userinfo.profile'],
  'AUTH_PARAMS': {'access_type': 'online'},
  'PROVIDER_KEY': get_env("GOOGLE_PROVIDER_KEY"),                # Stored in secrets.env
  'PROVIDER_SECRET_KEY': get_env("GOOGLE_PROVIDER_SECRET_KEY"),  # Stored in secrets.env
}
SOCIALACCOUNT_PROVIDERS['google'] = _GOOGLE # This isn't enabled in biostar.settings.base

# Etc ...
```

**Comment by nmvega** [comment]
Everything I did in my previous comment was find. I discovered the issue was my SITE_ID needed adjusting (from default of 1 to 3).
