### ISSUE TITLE
Upgrades to packages .../conf/requirements/frozen.txt ...

### ISSUE THREAD

**Issue by nmvega** [ialbert/biostar-central#442]
Hi there again ...

Question ...

Have any of the items/packages in `./conf/requirements/frozen.txt` (or, alternatively, the combination of `./base.txt` + `./deploy.txt`) been upgraded to newer versions for the [biostars.org](https://www.biostars.org/) site **and** that did **not** require modifications to the application to accommodate it?

One reason I ask is that I notice that `celery beat` doesn't restart (as initiated by supervisord) if it finds a PID file for it laying around. Little things like that that an upgrade can fix in lieu of workarounds. Or upgrades simply for better performance, security fixes or stability. Again, none that would require modification to the biostar app.

Thank you!

**Comment by ialbert** [comment]
Alas I don't know - there was an effort to move to django 1.9 but by the time it got close to completion django moved to 1.10, and now django is at 1.11.

Unfortunately the co-dependecy web is deep and tangled.Back when I designed the system I was not as aware as I am today just how important it is to reduce and minimize that. I would recommend sticking with the current recommendations.

**Comment by nmvega** [comment]
Thank you. I hear you on the co-dependency web (I like that description of it -- nothing could be truer). Closing ticket. Thanks!
