### ISSUE TITLE
Django 1.11 support?

### ISSUE THREAD

**Issue by Logmytech** [ialbert/biostar-central#447]
Does this support Django 1.11?

What is the latest Django version that is supported?

**Comment by ialbert** [comment]
Asking questions about the code are not valid issues.

The issue tracking should be solely used for the purpose it was invented.

 So we won't anwer this question as not encourage this type of content.

**Comment by Logmytech** [comment]
Is there any place else I can ask about the code?

Is there a meta for Biostars?

**Comment by ialbert** [comment]
It is a catch 22 - there isn't. The answer is in the requirements file. Every version is pinned.

There is also a branch called 1.9 that attempted to bring it to Django 1.9
