### ISSUE TITLE
Moderator templates are not in Markdown yet

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#449]
I encountered this while I tried to edit the close-post message. Once a post is closed using the dialog on the site, if we edit the closure comment added, it is in HTML with `<p>` tags, and not in Markdown. All new posts added are in Markdown by default, whereas a lot of older posts behave the way this one did, so I'm guessing that the auto-generated comments spawned by moderating actions are rendered into HTML by an older engine maybe?

**Comment by ialbert** [comment]
I will investigate.

**Comment by Natay** [comment]
This issue has been fixed in the most current release of biostars.
