### ISSUE TITLE
malformed biostar rss feeds

### ISSUE THREAD

**Issue by wm75** [ialbert/biostar-central#450]
Hi,
as posted earlier today at https://biostar.usegalaxy.org/p/26521/ I cannot follow biostar.usegalaxy rss feeds since about a week (last successful download was on 24 Jan) with Thunderbird anymore.

Here's what Thunderbird reports as the problem, *e.g.*,  for https://biostar.usegalaxy.org/feeds/latest/

> This feed does not validate.
> 
>     line 34, column 88: guid must be a full URL, unless isPermaLink attribute is false: 26512 (19 occurrences) [help]
> 
>         ... 2018 17:30:29 +0000</pubDate><guid>26512</guid></item><item><title>Loadi ...
>                                                      ^
> 
>     line 187, column 1: XML parsing error: <unknown>:187:1: not well-formed (invalid token) [help]
> 
>         mî¤øJV             w     	     ÿ

Jen from the Galaxy team asked me to open an issue for this here and I hope it's the right place.

**Comment by ialbert** [comment]
Yes it is the right place. We'll take a look.
