### ISSUE TITLE
unable to login via guthub

### ISSUE THREAD

**Issue by lakhujanivijay** [ialbert/biostar-central#451]
Hi 
My biostar url is https://www.biostars.org/u/26377/

For the past few days, I am unable to login into biostars using my github login

Are all users experiencing the same issue?

**Comment by RamRS** [comment]
GitHub has faced a mammoth DDiS attack. That could be behind this.

--
Ram
________________________________

**Comment by ialbert** [comment]
Looks like GitHub removed crypto features that we relied on

https://githubengineering.com/crypto-removal-notice/

For this reason, I have now removed GitHub login as an option.

Users can still use the same account that they did with GitHub but they will need to set a local password using the same email via the Forgot Password link.
