### ISSUE TITLE
hmac issue with signup mailing 

### ISSUE THREAD

**Issue by thomastinu** [ialbert/biostar-central#452]
I'm getting the following error while using the django.core.mail.backends.smtp.EmailBackend 👍 
  
> File "/usr/local/lib/python2.7/smtplib.py", line 607, in login
>     (code, resp) = self.docmd(encode_cram_md5(resp, user, password))
>   File "/usr/local/lib/python2.7/smtplib.py", line 571, in encode_cram_md5
>     response = user + " " + hmac.HMAC(password, challenge).hexdigest()
>   File "/usr/local/lib/python2.7/hmac.py", line 75, in __init__
>     self.outer.update(key.translate(trans_5C))
> TypeError: character mapping must return integer, None or unicode

Is there a fix for this issue? My python version is 2.7.11

**Comment by ialbert** [comment]
I don't think this error is related to biostar, looks like you might have some sort of internal version conflict between the python modules.  Perhaps you have multiple versions of Python installed that are not sufficiently isolaterd.

**Comment by Toxu-ru** [comment]
@ialbert Got an error - is it similar? Or the matter is completely different.

```
TypeError at /accounts/password/reset/
character mapping must return integer, None or unicode

character mapping must return integer, None or unicode
/usr/lib/python2.7/hmac.py in __init__, line 75
/usr/bin/python
Python Version: | 2.7.12
```

**Comment by ialbert** [comment]
not sure why that happens, I found this:

https://stackoverflow.com/questions/20849805/python-hmac-typeerror-character-mapping-must-return-integer-none-or-unicode/20862445
