### ISSUE TITLE
postimg.org links broken

### ISSUE THREAD

**Issue by obigriffith** [ialbert/biostar-central#453]
One of the (previously?) suggested options for free hosting of images in posts was postimg.org. It seems this service is having some issues with their business model and related to that having some issues with ownership of their domain name. Currently all links involving postimg.org are broken but can be recovered by changing to postimg.cc. Is this something that could be fixed site wide? I started manually changing some but (A) realized this is a huge task and (B) had issues with some comment posts where they are now over the comment character limit. That makes it even a bigger task if I must simultaneously edit down posts and fix links.

**Comment by ialbert** [comment]
I will investigate. In principle the fix is super simple, crawl then a replace of text that contains the string. In practice there may be practical issues. But I'll investigate in a few days.

**Comment by Natay** [comment]
This issue has been fixed in the latest Biostar, we can host images locally now.
