### ISSUE TITLE
Better guide to correctly insert a figure 

### ISSUE THREAD

**Issue by zhilongjia** [ialbert/biostar-central#455]
Frequently, users insert figures incorrectly at biostars as they use a page link instead of **a figure link**. An enhancement can be made.

In the `biostar/static/lib/pagedown/Markdown.Editor.js`
1. Change 
`imagedialog: "<p><b>Insert Image</b></p><p>http://example.com/images/diagram.jpg \"optional title\"<br><br>Need <a href='http://www.google.com/search?q=free+image+hosting' target='_blank'>free image hosting?</a></p>",`
to 
`imagedialog: "<p><b>Insert Image</b></p><p>https://image.ibb.co/cXURsS/04_image_link_added<b>.png</b> \"optional title\"<br><br><b>Note: The inserted link must be end with .jpg or .png!</b><br><br>Need <a href='http://www.google.com/search?q=free+image+hosting' target='_blank'>free image hosting?</a></p>",`

2. Also, A tip at the image default text.
Change
`var imageDefaultText = "http://";`
to
`var imageDefaultText = "https://image.ibb.co/fHRT6n/05_direct_links.png";`

Probably, a funciton identifying whether an url link inserting has a figure basename (like png) during inserting a figure will effectively solve the issue.

ref: https://www.biostars.org/p/309884/#318092

Thank you.

**Comment by RamRS** [comment]
Changing the image default text to an actual image can confuse users and result in that image being added by mistake a lot of times.

**Comment by Natay** [comment]
This is has been revised and corrected in the most current release of Biostars.
