### ISSUE TITLE
subcommands not working

### ISSUE THREAD

**Issue by me-kell** [ialbert/biostar-central#458]
After an installation following the install instructions `python manage.py help` is not showing biostar commands. It only shows django subcommands.

In `biostar/server/management/commands` I see all `*.py` files but only two `*.pyc` files: `__init__.pyc` and `initialize_site.pyc`.

Some hint?

**Comment by ialbert** [comment]
sounds like your installation is not picking up the correct settings file.

**Comment by me-kell** [comment]
Thank you very much. That was it.
With `python manage.py --settings="biostar.settings.base" help` it works fine.
