### ISSUE TITLE
Error in getBM(attributes = c("ensembl_gene_id_version", "mgi_symbol", 

### ISSUE THREAD

**Issue by hkyagnes** [ialbert/biostar-central#460]
library(biomaRt)

#for res1
res1$ensembl <- sapply (strsplit(rownames(res1), split="\\+"), "[", 1)
ensembl <- useMart("ensembl", dataset="mmusculus_gene_ensembl")
genemap <-getBM(attributes = c("ensembl_gene_id_version", "mgi_symbol", "description"),
                filter ="ensembl_gene_id_version",
                values = res1$ensembl,
                mart=ensembl)

Error in getBM(attributes = c("ensembl_gene_id_version", "mgi_symbol",  : 
  The query to the BioMart webservice returned an invalid result: biomaRt expected a character string of length 1. 
Please report this on the support site at http://support.bioconductor.org
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> getBM

**Comment by RamRS** [comment]
I don't think this is relevant here. If this is a bioinformatics question, please post on https://www.biostars.org/ or https://support.bioconductor.org/

Please close this issue as it is irrelevant to the GitHub repository.
