### ISSUE TITLE
I guess this is moved to https://github.com/biostars/biostar-engine right?

### ISSUE THREAD

**Issue by bufferoverflow** [ialbert/biostar-central#462]
It's not obvious for people that this is no longer the main repo for biostars or is it still?

**Comment by ialbert** [comment]
No, this will remain the main repository. 

The biostar-engine will be merged into this repository once we reach a sufficiently advanced beta stage. 

The code was originally devised to run recipes and the Q&A component was added later as a separate, standalone app. 

It was developed separately as not confuse people as it now consists of a collection of different web apps, one of which will be the forum Q&A.

**Comment by ialbert** [comment]
But it is true that for those interested in following the direction the site is taking should look at 

https://github.com/biostars/biostar-engine

the webapps developed via  the biostar-engine are currently deployed as:

http://test.biostars.org/

and as:

https://www.bioinformatics.recipes/

**Comment by bufferoverflow** [comment]
@ialbert Thanks for the details! I'm currently evaluating Q&A platforms, that's why I'm asking.

- Is the goal to have separate repositories for the components like biostar-qa and biostar-recipes?
- Should I place MRs on https://github.com/biostars/biostar-engine or does the development happen somewhere else? 
- Do you see usage of the Q&A component outside biostar eco system as a valid option?

**Comment by ialbert** [comment]
The current plan is to develop a collection of apps that are independently mountable. 

There will be a Q&A app, a recipe app, an email newsletter app, and a static website generator app. One may choose to mount just one, or even all of them all at the same time.

All apps are developed in a single repository to avoid ending up reimplementing common components and to ensure that everything keeps working well together. The apps all share some commonalities, (user accounts, messaging etc). The recipes are pretty much completed. The Q&A will be done this summer if all goes well. 

We will merge the biostar-engine into biostar-central once we switch over the main site. Until then the engine is the repository where we track information on the new code.

**Comment by Toxu-ru** [comment]
@ialbert  Hmm. And on https://www.biostars.org/ which branch is there? Below it says: Powered by Biostar version 2.3.0
https://github.com/ialbert/biostar-central/tree/biostar2016 ?

**Comment by ialbert** [comment]
yes the main biostar works off an the 2016 branch.

**Comment by Natay** [comment]
Biostar is now using the latest master branch, the 2016 branch is legacy code.
