### ISSUE TITLE
cannot sign up to post new post

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#490]
Is it possible for this function?
Thanks.

**Comment by Natay** [comment]
You can sign up manually using your email. The social singups require public and private keys to work. We plan to take out the social siginup options if there are no keys provided in the SOCIAL_CLIENTS variable of the settings file.

**Comment by piggybit** [comment]
tks, but maybe we need to fix it since i sign up then not able to login, always have "wrong password".

**Comment by Natay** [comment]
Found the problem, save() was not being called after password has been set. I added a fix it and will open a pull request.

**Comment by piggybit** [comment]
Thanks Natay.
