### ISSUE TITLE
cannot post new question in forum

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#503]
Hi.
Seems there is no POST button in new post.
Could you check? Thank you very much.

![Screenshot from 2019-11-09 23-54-43](https://user-images.githubusercontent.com/55419584/68532134-667bab00-034c-11ea-9ffb-f1d24490f080.png)

**Comment by Natay** [comment]
Hey @piggybit , the problem comes from the form container having a smaller height than the form, this is not apparent when the forum is populated. Thanks for letting us know, I will open a pull request for a fix.

**Comment by piggybit** [comment]
tks @Natay, appreciate it!

**Comment by ialbert** [comment]
only close when the problem is fixed

**Comment by piggybit** [comment]
i can see new form now, but cannot submit the button. Here is the snapshot.

![cannot save new question](https://user-images.githubusercontent.com/55419584/68629569-e9506180-0516-11ea-9eb4-76f2d8ec6d91.png)

**Comment by Natay** [comment]
@piggybit , i  recreated your posts and it tells me the title is too short. The error message appears  at the top and disappears too quickly, so you might have not seen it. If you pull from the most recent version of this repo the message appears near the save button.

**Comment by piggybit** [comment]
i pulled latest version, and added more content but still the same.

![image](https://user-images.githubusercontent.com/55419584/68635354-d9427d00-052a-11ea-9463-d84101419979.png)

**Comment by piggybit** [comment]
i add more content and seems the form is not enough:

![image](https://user-images.githubusercontent.com/55419584/68636457-1d834c80-052e-11ea-9551-7d649b5dd96b.png)

**Comment by piggybit** [comment]
@Natay can i help anything here?
Thanks.

**Comment by Natay** [comment]
@piggybit , what actually happens when you press the save button? any errors or messages? or nothing happens? if so did you initialize correctly by calling `make init`? your static files may not be collected. I tried to recreate this may times but it all works.

**Comment by piggybit** [comment]
@Natay Strange! Nothing happens when i press the Save, and no even message pops up.

**Comment by piggybit** [comment]
i tried recreating from beginning with conda, and here is the output of #make forum test, still have the same symptom.
![Screenshot from 2019-11-19 09-06-13](https://user-images.githubusercontent.com/55419584/69110098-32bb2680-0aac-11ea-91a5-2e241f448b87.png)


$ make forum test
DJANGO_SETTINGS_MODULE=biostar.forum.settings
DJANGO_APP=biostar.forum
DATABASE_NAME=database.db
DJANGO_SETTINGS_MODULE=biostar.forum.settings
DJANGO_APP=biostar.forum
#python manage.py test biostar.forum --settings biostar.forum.settings -v 2 --failfast
coverage run manage.py test biostar.forum --settings biostar.forum.settings -v 2 --failfast
Secrets module not imported: No module named 'conf.run.secrets'
WARNING	2019-11-19 02:03:07,535	decorators.<module>	9	uwsgi decorators not found, tasks are synchronous	
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: allauth, compressor, github, google, humanize, messages, pagedown, rest_framework, staticfiles
  Apply all migrations: account, accounts, admin, auth, contenttypes, emailer, forum, mailer, sessions, sites, socialaccount, taggit
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_email_max_length... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20190403_0020... OK
  Applying accounts.0003_message_prefs... OK
  Applying accounts.0004_mailing_list... OK
  Applying accounts.0005_message_prefs... OK
  Applying accounts.0006_message... OK
  Applying accounts.0007_profile_prefs... OK
  Applying accounts.0008_message_body... OK
  Applying accounts.0009_add_spamrole... OK
  Applying accounts.0010_watched_tags... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying emailer.0001_initial... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying forum.0001_initial... OK
  Applying forum.0002_add_toplevel... OK
  Applying forum.0003_subtype... OK
  Applying forum.0004_indexed... OK
  Applying forum.0005_chat... OK
  Applying mailer.0001_initial... OK
  Applying mailer.0002_auto_20150720_1433... OK
  Applying mailer.0003_messagelog_message_id... OK
  Applying mailer.0004_auto_20190920_1512... OK
  Applying sessions.0001_initial... OK
  Applying socialaccount.0001_initial... OK
  Applying socialaccount.0002_token_max_lengths... OK
  Applying socialaccount.0003_extra_data_default_dict... OK
  Applying taggit.0003_taggeditem_add_unique_index... OK
INFO	2019-11-19 02:03:08,630	apps.init_site	104	db.engine=django.db.backends.sqlite3, db.name=file:memorydb_default?mode=memory&cache=shared	
INFO	2019-11-19 02:03:08,630	apps.init_site	105	email.backend=django.core.mail.backends.locmem.EmailBackend	
INFO	2019-11-19 02:03:08,630	apps.init_site	106	default.email=Admin User <admin@localhost>	
INFO	2019-11-19 02:03:08,631	apps.init_site	116	site.name=Biostar Forum, site.domain=localhost	
INFO	2019-11-19 02:03:08,631	apps.init_users	73	Setting up admin users.	
INFO	2019-11-19 02:03:08,751	apps.init_users	88	Created admin user: admin@localhost, admin-1	
INFO	2019-11-19 02:03:08,752	apps.init_social	49	Creating social social app: Google	
INFO	2019-11-19 02:03:08,755	apps.init_social	49	Creating social social app: GitHub	
System check identified no issues (0 silenced).
test_ajax_search (biostar.forum.tests.test_ajax.PostTest) ... 1 True
ok
test_ajax_subs (biostar.forum.tests.test_ajax.PostTest) ... ok
test_ajax_tags_search (biostar.forum.tests.test_ajax.PostTest) ... ok
test_ajax_users_search (biostar.forum.tests.test_ajax.PostTest) ... ok
test_ajax_vote (biostar.forum.tests.test_ajax.PostTest)
Test the ajax voting using POST request ... ok
test_digest (biostar.forum.tests.test_ajax.PostTest) ... ok
test_drag_and_drop (biostar.forum.tests.test_ajax.PostTest) ... ok
test_inplace_create (biostar.forum.tests.test_ajax.PostTest) ... ok
test_inplace_edit (biostar.forum.tests.test_ajax.PostTest) ... ok
test_inplace_form (biostar.forum.tests.test_ajax.PostTest) ... ok
test_similar_posts (biostar.forum.tests.test_ajax.PostTest) ... ok
test_answer_moderation (biostar.forum.tests.test_moderate.PostTest)
Test answer moderation. ... ok
test_comment_moderation (biostar.forum.tests.test_moderate.PostTest)
Test comment moderation. ... ok
test_duplicate_post (biostar.forum.tests.test_moderate.PostTest)
Test duplicate post moderation ... ok
test_toplevel_moderation (biostar.forum.tests.test_moderate.PostTest)
Test top level post moderation. ... ok
test_public_pages (biostar.forum.tests.test_navigation.ForumNavigation)
Checking public forum pages ... /
INFO	2019-11-19 02:03:09,929	middleware.middleware	36	time=114ms path=/	
/bookmarks/
INFO	2019-11-19 02:03:09,941	middleware.middleware	36	time=9ms path=/bookmarks/	
/following/
INFO	2019-11-19 02:03:09,960	middleware.middleware	36	time=16ms path=/following/	
/myposts/
INFO	2019-11-19 02:03:09,986	middleware.middleware	36	time=23ms path=/myposts/	
/votes/
INFO	2019-11-19 02:03:09,995	middleware.middleware	36	time=6ms path=/votes/
/new/post/
INFO	2019-11-19 02:03:10,008	middleware.middleware	36	time=11ms path=/new/post/	
/community/
INFO	2019-11-19 02:03:10,022	middleware.middleware	36	time=11ms path=/community/	
/b/list/
INFO	2019-11-19 02:03:10,031	middleware.middleware	36	time=7ms path=/b/list/	
/b/view/1c55ebcb/
INFO	2019-11-19 02:03:10,041	middleware.middleware	36	time=7ms path=/b/view/1c55ebcb/	
/p/p1/
INFO	2019-11-19 02:03:10,072	middleware.middleware	36	time=28ms path=/p/p1/
/edit/post/p1/
INFO	2019-11-19 02:03:10,084	middleware.middleware	36	time=9ms path=/edit/post/p1/	
/new/comment/p1/
INFO	2019-11-19 02:03:10,089	middleware.middleware	36	time=2ms path=/new/comment/p1/	
ok
test_comment (biostar.forum.tests.test_post.PostTest)
Test adding comment using POST request ... ok
test_comment_traversal (biostar.forum.tests.test_post.PostTest)
Test comment rendering pages ... ok
test_edit_post (biostar.forum.tests.test_post.PostTest) ... ok
test_markdown (biostar.forum.tests.test_post.PostTest)
Test the markdown rendering ... <p><a href="http://test.biostars.org/accounts/profile/user-2/">http://test.biostars.org/accounts/profile/user-2/</a></p>
<p><a href="http://test.biostars.org/p/p371285/">http://test.biostars.org/p/p371285/</a></p>

ok
test_post_answer (biostar.forum.tests.test_post.PostTest) ... Created post=2
ok
test_post_create (biostar.forum.tests.test_post.PostTest)
Test post creation with POST request ... Created post=2
ok

----------------------------------------------------------------------
Ran 22 tests in 1.494s

OK
Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
coverage html --skip-covered

**Comment by Natay** [comment]
@piggybit looks like the tests are running fine, what operating system are you using?

**Comment by piggybit** [comment]
I have ubuntu 18.04

**Comment by piggybit** [comment]
Today i tried "make forum reset" and able to post  a new post. so we can close this ticket please.
Thank you.

`$ make forum reset
DJANGO_SETTINGS_MODULE=biostar.forum.settings
DJANGO_APP=biostar.forum
DATABASE_NAME=database.db
# Delete the database, logs and CACHE files.
# Keep media and spooler.
rm -rf export/logs/*.log
rm -f export/db/database.db
rm -rf export/static/CACHE
rm -rf *.egg
rm -rf *.egg-info
DJANGO_SETTINGS_MODULE=biostar.forum.settings
python manage.py collectstatic --noinput -v 0  --settings biostar.forum.settings
Secrets module not imported: No module named 'conf.run.secrets'
WARNING 2019-11-21 23:50:06,588 decorators.<module>     9       uwsgi decorators not found, tasks are synchronous       
python manage.py migrate -v 0  --settings biostar.forum.settings
Secrets module not imported: No module named 'conf.run.secrets'
WARNING 2019-11-21 23:50:06,933 decorators.<module>     9       uwsgi decorators not found, tasks are synchronous       
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
INFO    2019-11-21 23:50:07,170 apps.init_site  104     db.engine=django.db.backends.postgresql, db.name=ar_sandbox     
INFO    2019-11-21 23:50:07,170 apps.init_site  105     email.backend=django.core.mail.backends.console.EmailBackend    
INFO    2019-11-21 23:50:07,170 apps.init_site  106     default.email=Admin User <admin@localhost>      
INFO    2019-11-21 23:50:07,171 apps.init_site  116     site.name=Biostar Forum, site.domain=localhost  
INFO    2019-11-21 23:50:07,171 apps.init_users 73      Setting up admin users. 
INFO    2019-11-21 23:50:07,212 apps.init_users 93      Admin user: admin@localhost, admin-2 exists.  `
