### ISSUE TITLE
RelatedObjectDoesNotExist at /community/

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#504]
Hi.
I logged in, but get this error when accessing to /community.
Could you check.
Thank you.
-----------------
RelatedObjectDoesNotExist at /community/
User has no profile.
Request Method: | GET
-- | --
http://127.0.0.1:8000/community/
2.2.7
RelatedObjectDoesNotExist
User has no profile.

**Comment by Natay** [comment]
@piggybit , thanks for the report we are taking a deeper look into it. 

Can you try running `make forum reset` to see if the problem persists?

**Comment by piggybit** [comment]
@Natay i never tried that, instead i open the project via pycharm. what's the purpose of #make forum reset?
Thanks.

**Comment by Natay** [comment]
@piggybit , it refreshes the database so any corrupted data is gone. 
But do not run that yet, I want to know more about the error so i can recreate it.

Can you give me a traceback of the error? and maybe what commands/actions you made before it occurred?

**Comment by ialbert** [comment]
I would recommend following the install instructions to run the server - that being said it should work no matter how you launch it. 

Some environmental variables need to be set and when you launch from PyCharm it can be more difficult to figure out where the code runs from and what variables are active.

**Comment by piggybit** [comment]
i pulled latest version, and use Pycharm and it's working. so i think we can close.

**Comment by piggybit** [comment]
recently, again, i face this issue, tried "$make forum reset" but issue still exists.

**Comment by Natay** [comment]
Did you do anything differently from when it was working for you 10 days ago?  

Other than `make forum reset` ?

**Comment by piggybit** [comment]
i created some users.
Seems it's related to my postgres which is used for another task, might be the inconsistent in users list.
Let me re-check the database.

**Comment by piggybit** [comment]
fixed, i go to the admin page, and correct profile of a user which seems to be mis-configured.
it fixes the issue.
