### ISSUE TITLE
Not able to social authenticate

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#510]
Here is the snapshots, for both Google and Github:
![Git_](https://user-images.githubusercontent.com/55419584/69194327-715bea00-0b5b-11ea-9ad2-a5fac6ea193d.png)
![google_](https://user-images.githubusercontent.com/55419584/69194329-71f48080-0b5b-11ea-9e59-08b613eea03f.png)

**Comment by Natay** [comment]
Did you set up the public and private keys for the OAuth clients in your settings?

**Comment by piggybit** [comment]
i did, let me re-check that. i might miss something here, sorry.

**Comment by Natay** [comment]
We are using django-allauth for social logins. 

The site comes with demo public and private keys but these need to be replaced with your own.

Here is the documentation from django-allauth on how to set things up : https://django-allauth.readthedocs.io/en/latest/installation.html
