### ISSUE TITLE
Change in new post method

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#511]
Hi @Natay.

Currently i can see the flow: User login -> new post.
Can we have alternative method: anonymous user can post new question, but only logged in user can post an answer?

Thanks.

**Comment by Natay** [comment]
We'll see how practical it is to implement anonymous users posting new questions. 

My reservation comes from the fact that this further opens the doors to spammers.

**Comment by piggybit** [comment]
It's true potential for spammer.

Is there any way to track anonymous user, so we can limit each anonymous
user to have only one anonynous new post?

**Comment by Natay** [comment]
This would require us to keep some sort of sessions information on anonymous users, which could lead to the database growing exponentially.
