### ISSUE TITLE
cannot login the admin page

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#513]
Hi.

I tried to create admin page, and a super user, but seems i cannot login to.
I also tried to use super user to login to normal login page but unable to do it with error "email doesn't exist".
Do you have any instruction?

```
$ python3 manage.py createsuperuser
Secrets module not imported: No module named 'conf.run.secrets'
WARNING 2019-11-21 23:29:46,854 decorators.<module>     9       uwsgi decorators not found, tasks are synchronous       
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'admin' isn't unique. You may not be able to reverse all URLs in this namespace
Username (leave blank to use 'thang'): superadmin
Email address: superadmin@gmail.com
Password: 
Password (again): 
Superuser created successfully.

```
![Screenshot from 2019-11-22 06-46-47](https://user-images.githubusercontent.com/55419584/69386046-f24de980-0cf3-11ea-9dbb-f9e3fa075e65.png)

**Comment by Natay** [comment]
Use the email : `superadmin@gmail.com` instead of the username. 

We use emails authenticate users. We will change the template to ask for `Email` instead of `Username` to avoid confusion.

**Comment by piggybit** [comment]
resolved, so close.
