### ISSUE TITLE
unable to change the avatar?

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#514]
Hi.
I cannot find the way to change the avatar, is the function available yet?
Thanks.

**Comment by Natay** [comment]
We use gravatar to set the avatar. 

If you want to change the avatar for a single user, you need to register your email with gravatar and set your avatar image there. 

Here is the gravatar site to do that: https://en.gravatar.com/

**Comment by piggybit** [comment]
cool.
tks Natay.
