### ISSUE TITLE
No editor in the reply

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#535]
Merry Christmas!
I wonder why we don't have the editor in the Reply, while it's there in the new post?
Thank you.
**REPLY with no editor**
![Reply](https://user-images.githubusercontent.com/55419584/71215946-ac347780-22eb-11ea-8b59-b80da56028dd.png)

**New Post has the editor**
![NewPost](https://user-images.githubusercontent.com/55419584/71215986-bf474780-22eb-11ea-8002-6f858d46ceed.png)

**Comment by Natay** [comment]
Thank you for brining this to our attention, we will look into it. 
Merry Christmas

**Comment by piggybit** [comment]
btw, when i check pagedown, it has no support for image drop-drag.. which is really weird for recent days.
Should we move to another WYSIWYG Editors?

**Comment by piggybit** [comment]
@Natay  i found django-ckeditor seems to be good wysiwyg for django, with very active community. 
However, when i look into inplace_form.html, we have a mix of custom Mardown and UI and could make it hard to migrate to any other WYSIWYG, so do i wonder if you have any plan to migrate?

**Comment by ialbert** [comment]
we will stay with Markdown based editors. We used to have CKEditor in some early versions but turned out to cause more trouble than worth. Code was hard to edit, html gets wonky etc.

Our audience should be technical enough to be able to understand and deal with Markdown.

**Comment by piggybit** [comment]
@Natay i still do not see pagedown editor in new post and in reply part, could you check? Thanks.

![Screenshot from 2020-02-04 00-44-12](https://user-images.githubusercontent.com/55419584/73676771-8a4e5300-46e7-11ea-9cfd-49f390c73127.png)
![Screenshot from 2020-02-04 00-43-47](https://user-images.githubusercontent.com/55419584/73676782-8e7a7080-46e7-11ea-8376-f88f916b2512.png)

**Comment by ialbert** [comment]
thanks for finding interesting bugs, @piggybit,

the reasons for this are a bit more subtle, we are on it


 we added you to the contributor's list, let us know if you don't want to be listed

https://github.com/ialbert/biostar-central/blob/master/contributors.md

**Comment by piggybit** [comment]
Thank you for your answer @ialbert .
I am glad to be in the list, even though i believe my contribution is just very little, hope in future i can contribute more :).
