### ISSUE TITLE
Mobile display

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#537]
Hello.
Merry Christmas and Happy New Year!
I just check the website via my mobile and can see the display is a bit hard to see, the Search Icon is not there.

Maybe we might need to adjust mobile view in community/ link.
Regards.

![Screenshot_20191223-043302_Chrome](https://user-images.githubusercontent.com/55419584/71327740-d6ca3e80-253e-11ea-9a72-14e5205a5c1b.jpg)

**Comment by Natay** [comment]
Merry Christmas and Happy New Year to you as well. 
We are still working on the phone display, thanks for bringing this to our attention.

**Comment by piggybit** [comment]
Thanks @Natay.
Btw, Semantic-UI is no longer active project, so keep using it might come to some bugs in display. Do you have any plan to migrate to new CSS framework?

**Comment by piggybit** [comment]
i found Fomantic-UI is forked from Semantic-UI, and is compatible with old SUI, so one good option is Fomantic-UI.

**Comment by ialbert** [comment]
Good to know, thanks for tracking this down @piggybit technically speaking the CSS is not like other code that must be updated otherwise it might not work, but it is good to know that there is a migration path.
