### ISSUE TITLE
fake email can register?

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#539]
Hello.
I realized i can register with just fake email, so i assume it's possibly for spamming.
Do we need to setup a mechanism for email validating?

Thanks.

**Comment by Natay** [comment]
Registering with fake emails is possible, but most spammers we see actually have valid gmails.

We do have an email conformation system that serves as a validator. This works by sending an email, containing a link, to the provided address. The user simply clicks the link in the email to verify the address. This feature will be turned on soon in the forum.

In the near future, new users will need verified emails before posting questions. We think this will greatly reduce spam.

**Comment by piggybit** [comment]
tks Natay!

**Comment by piggybit** [comment]
@Natay so now we're using django-mailer?

**Comment by Natay** [comment]
Yes, we use django-mailer to queue emails and send them in batches.

**Comment by piggybit** [comment]
tks Natay :)!
