### ISSUE TITLE
Develop version of Pagedown with image upload

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#572]
Good evening.
Yesterday pagedown just has the Develop version with image upload function. 
https://github.com/timmyomahony/django-pagedown/issues/32#issuecomment-585305112

Do you mind to test it?

Thank you.

**Comment by piggybit** [comment]
Hello @ialbert 
Are we testing this dev version of Pagedown? So i can lend a hand.

**Comment by ialbert** [comment]
right now our lives are a bit too hectic, so this is not being worked on

**Comment by piggybit** [comment]
yeah, i know, take care and be safe! God bless us all!

**Comment by piggybit** [comment]
@ialbert recent days, looking into image upload, if we use CDN or cloud storage like AWS S3 then the security should be fixed.
https://docs.djangoproject.com/en/3.0/topics/security/#user-uploaded-content-security

If so, for django-ckeditor it has the integration with S3 via django-storage, that might somehow assist us on this request. How do you think about that?

**Comment by piggybit** [comment]
@ialbert there's new release of pagedown with image upload.
Would we migrate with this new version?

**Comment by ialbert** [comment]
we'll evaluate the new functionality

**Comment by Natay** [comment]
@piggybit we are trying this out in the coming week in the recipes platform. It will be deployed in the forum as well. Thanks for letting us know.

**Comment by piggybit** [comment]
Super great news, thanks @Natay and @ialbert for working on this.

**Comment by ialbert** [comment]
The feature was added by @Natay  to the recipes app, will be added to the forum as well:

https://github.com/ialbert/biostar-central/commit/baedf56bfd5de3645305de74de9087e3b45cd2be
