### ISSUE TITLE
Code not being rendered properly?

### ISSUE THREAD

**Issue by django-nerd** [ialbert/biostar-central#578]
I have deployed biostar forum on local machine and also on cloud. I am facing same issue with codes.

Say I am typing an answer using the editor.. I pasted code `" if (n <= 5) cout << 5; "` on the editor body. It renders correctly in preview too like it should.
But as soon as I post this, symbols are getting replaced with their entity symbols.

Following image is final view of example mentioned above. I am clueless about how to fix it?
![image](https://user-images.githubusercontent.com/61336355/75082538-18289b80-553a-11ea-9083-69101ec4d315.png)

**Comment by ialbert** [comment]
we know about this, just a temporary issue due to an oversight, will be fixed in next commit, not to worry

**Comment by Natay** [comment]
This has been fixed in the most current release of Biostar.
