### ISSUE TITLE
Unaccent search in Postgresql (ASCII)

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#592]
Hello.
I've been working on this, created extension on Postgres

> CREATE EXTENSION unaccent

Check on Postgresql server side, it's working.

> SELECT *
from forum_post
where unaccent(title) ilike '%ao%'

 But have no idea why in production cannot search using unaccent?
I am using psycopg2 for Posgres connection, while we use Whoosh for search, do we have to configure anything on this side?

**Comment by piggybit** [comment]
@ialbert do you have any idea on this? 
Thank you.

**Comment by ialbert** [comment]
sorry, this has nothing to do with our system - your system must be set up differently, we don't search directly on Postgres our code uses Whoosh.

**Comment by piggybit** [comment]
@ialbert sorry i didn't explain it clearly, i use Whoosh with backend is psycopg2 for Postgres, but somehow when i querry the unaccent direcly in Postgres side it's OK, but via search via Whoosh it doesn't work.

**Comment by ialbert** [comment]
whoosh does not use postgreql, it is a python based search engine, the index the search all takes place in Python
