### ISSUE TITLE
Upstream prematurely closed connection...

### ISSUE THREAD

**Issue by Toxu-ru** [ialbert/biostar-central#595]
In development mode, sending emails via SMTP (Yandex) is in progress. Moved the server to production.

`2020/03/19 10:58:22 [error] 7669#7669: *1 upstream prematurely closed connection while reading response header from upstream, client: 149.62.15.148, server: test.ru, request: "POST /accounts/password/reset/ HTTP/1.1", upstream: "http://unix:/tmp/biostar.sock:/accounts/password/reset/", host: "test.ru", referrer: "http://test.ru/accounts/password/reset/"`

The config is such.

```
upstream biostar_server {
    server unix:/tmp/biostar.sock fail_timeout=0;
    # For a TCP configuration:
    # server 192.168.0.7:8000 fail_timeout=0;
}

# When no server names match then crash out.
server {
   return 404;
}

server {
    listen 80;
    client_max_body_size 5M;
    server_name test.ru;
	include /etc/nginx/vhosts-resources/test.ru/*.conf;
	access_log /var/www/httpd-logs/test.ru.access.log;
    keepalive_timeout 25s;

    # Path for static files.
    root /var/www/test.ru/biostar/;

    access_log /var/www/test.ru/live/logs/nginx-access.log;
    error_log /var/www/test.ru/live/logs/nginx-error.log;

	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/test.ru/*.conf;

    location = /favicon.ico {
        alias    /var/www/test.ru/biostar/static/favicon.ico;
    }

    location = /sitemap.xml {
        alias    /var/www/test.ru/biostar/static/sitemap.xml;
    }

    location = /robots.txt {
        alias    /var/www/test.ru/biostar/static/robots.txt;
    }

    location /static/ {
        autoindex on;
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public";
        access_log off;
    }

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://biostar_server;
        proxy_buffering off;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }
}
```

I can’t understand what could be the reason.

How to look at the logs (nginx, gunicorn logs are written)

Thanks in advance.

**Comment by ialbert** [comment]
do you see an error on server side, beyond this log

a client making a connection can decide not to read the page, for example, if you go to a page but then navigate away before the page loads, this would be the error you get.

**Comment by Toxu-ru** [comment]
@ialbert Mail is not sent. When recovering a password, for example. After 10 seconds of freezing, an error appears - 502 Bad Gateway.

Perhaps these errors show what is happening. But what to do, where to look, unfortunately I do not know.

~~~
error: [Errno 32] Broken pipe
[18/Mar/2020 14:57:21] "POST /accounts/password/reset/ HTTP/1.0" 500 59
----------------------------------------
error: [Errno 32] Broken pipe
Exception happened during processing of request from ('62.109.31.61', 36244)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/django/core/servers/basehttp.py", line 126, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------
~~~

**Comment by ialbert** [comment]
first see if you can send emails via the console handler. If that works, then the problem is the SMTP server that does not let you send the email.

there is a test_email command that lets you send email from command line to test the SMTP server

**Comment by Toxu-ru** [comment]
@ialbert I'm sorry, I'm trying to learn this application, but I do not see this command in ./manage.py help
```
[django]
    check
    cleanup
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    runfcgi
    runserver
    shell
    sql
    sqlall
    sqlclear
    sqlcustom
    sqldropindexes
    sqlflush
    sqlindexes
    sqlinitialdata
    sqlsequencereset
    startapp
    startproject
    syncdb
    test
    testserver
    validate

```

**Comment by ialbert** [comment]
Which version are you using?

On the current master when I do 

`python manage.py `

It prints the following:

```
...
[emailer]
    send
    subscribe
    test_email

[mailer]
    purge_mail_log
    retry_deferred
    send_mail

[recipes]
    add_access
    analysis
    api
...
```

**Comment by Toxu-ru** [comment]
I use the version from 2016.

**Comment by ialbert** [comment]
load up the same database with default configuration, it should have a test_email action

**Comment by Toxu-ru** [comment]
In general, I solved the problem. My fault, yaMdex was wrong in smtp settings - > smtp.yaNdex.ru.

But the team `test_email` I never found it. 

More question. How do I get Biostar to write error logs? nginx-error - yes. gunicorn-error - yes, but empty. And the Biostar log itself, I wonder where it is?

**Comment by ialbert** [comment]
The system uses the django logger, logging can be a bit obtuse, there are many destination, handlers and levels, depending on the setup.

https://docs.djangoproject.com/en/1.8/topics/logging/

**Comment by Toxu-ru** [comment]
Thanks. The issue has been resolved.
