### ISSUE TITLE
Emailer not working 

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#600]
Hello.

I registered with new email, email sent back to me to confirm, but when i copied the link to new tab and go, then it shows link is expired.

Btw, what's the mechanism for email? 

- Using django-mailer with default backend? Have you tried with AWS SES backend?- 

- Which app will send email? Emailer? 

- And what templates they're using to send? in emailer/templates/ or forum/templates/accounts/ or accounts/templates/ ?

Thank you very much.

**Comment by ialbert** [comment]
Sending emails is a somewhat complex topic as there could be multiple backends and email sending blocks the server (a worker thread cannot return until the email was sent). For that reason on top of the normal email sending, Biostar uses an asynchronous email sender.

That being said none of the code that you ask about is specific to Biostar, each is maintained separately by other organizations;

I would suggest you read up first on sending emails in general, here you can read up on what APIs can you use to send emails from SMTP to Amazon SES (these are the APIs that actually send the email):

https://docs.djangoproject.com/en/3.0/topics/email/#email-backends

Then read up on asynchronous email sending via django-mailer, this is the layer that makes email sending non-blocking:

https://github.com/pinax/django-mailer

Finally, the password reset is also maintained by the Django system (we provide overrides in the accounts apps) but the views all come from Django as seen here:

https://docs.djangoproject.com/en/3.0/topics/auth/default/#module-django.contrib.auth.views

**Comment by piggybit** [comment]
Thanks @ialbert  for very detailed explanation, let me go through them and get back later, if required.
