### ISSUE TITLE
Whoosh search functionality not working

### ISSUE THREAD

**Issue by nithilprodapt** [ialbert/biostar-central#631]
Hello. I've deployed the code on my local machine.
While searching for a specific post using search bar, it always displays "Searching for posts containing: *text*" **No posts found**. Any ideas on how to make it work?

Thanks.

**Comment by ialbert** [comment]
you have to run the indexing periodically:

    make forum index

to add the latest new posts since the last indexing 

    make forum reindex

to reindex all posts

**Comment by nithilprodapt** [comment]
@ialbert  got it. :) Thanks
