### ISSUE TITLE
Temporary suspension

### ISSUE THREAD

**Issue by ATpoint** [ialbert/biostar-central#685]
Given the recent event with one user (we talked about this) I'd appreciate a temporary suspension option for a fixed span of time, e.g. three days or even better a with option to specifiy days/hours, and then automatic reinstatement. There are currently no moderation options to give problematic users a timeout to cool down beyond permanent suspension. While permanent suspension might or might not be appropriate in a given situation, a temporary time-out should (and I think must) be possible if user behaviour involves offending behaviour to make a clear statement that certain language/attitude is not going to be tolerated.

**Comment by ialbert** [comment]
One problem with suspensions is that it takes away the possibility of corrective action by the user. 

If they have an overly antagonistic way of expressing themselves that perhaps they did not fully recognized, how would they fix that right there if they were suspended.

I would recommend a different solution, that is of flagged posts, where a post being flagged informs the author that some of the content is objectionable. That gives them the chance to fix that post.

Flagging could have various types: Incomplete, questionable language etc. thus could be applied to other problematic content as well. Of course the actions one would take would be different on the different flags. Perhaps we could discuss the types of flags and types of actions would be appropriate to take on a flag.
