### ISSUE TITLE
The Q & A platform: setup guide

### ISSUE THREAD

**Issue by 0mars** [ialbert/biostar-central#686]
Is there a guide to have the Q&A platform setup ?

I managed to run the application, but I cannot find the Q&A part, I'm not sure where to go from there!

**Comment by ialbert** [comment]
The makefile has demonstrations on how to mount each application.

Basically forum, recipes are separate applications that share user accounts and other common elements.

**Comment by 0mars** [comment]
I'm trying to reach the Q&A part of the platform, like the stackoverflow like features, just explaining my intetion

**Comment by ialbert** [comment]
To run the server with the applied variables use

`make forum serve`

or 

`make forum demo`

the variables apply only within that run that you invoke, it does not "stick" for the next run.

**Comment by 0mars** [comment]
That explains it, thanks a lot <3
