### ISSUE TITLE
Change default Port

### ISSUE THREAD

**Issue by wMeloFernandes** [ialbert/biostar-central#691]
It`s possible to change the default PORT or DOMAIN when run **make forum serve**?

**Comment by ialbert** [comment]
the command simply runs the standard `manage.py runserver` command that  comes with django

it has a number of options

https://docs.djangoproject.com/en/3.1/ref/django-admin/#runserver

**Comment by munchkindev** [comment]
I tried specifying the port in /biostar/settings.py and and /biostar/recipes/settings.py but it appears to have no effect. How do you specify the port?

**Comment by ialbert** [comment]
answered in 

https://github.com/ialbert/biostar-central/issues/709
