### ISSUE TITLE
Problem updating scripts

### ISSUE THREAD

**Issue by wMeloFernandes** [ialbert/biostar-central#702]
I`m updating inplace.js script but the changes dont impact the code.
Is There some command I should run to detect this changes?

**Comment by ialbert** [comment]
it is not clear what you mean. browsers don't always reload files, so make sure the page is not cached,

sometimes I open up the file under the full path and look at it in the browser to ensure the page is not cached

**Comment by ialbert** [comment]
add your script to the django compressor

https://django-compressor.readthedocs.io/en/stable/
