### ISSUE TITLE
How to host on 0.0.0.0?

### ISSUE THREAD

**Issue by munchkindev** [ialbert/biostar-central#709]
I want to host the biostars (forum) on 0.0.0.0 so it's publicly available.
To accomplish that I tried changing the IP in /biostar/settings.py to 0.0.0.0 but it appears to have not worked.
How do you properly do this?

**Comment by ialbert** [comment]
the host in the settings is just to let the site know where to point the links in emails, there is no way to tell from inside a program what address it looks like from the outside.

to actually bind to a different port you need to run manage.py with the correct port number. 

```
python manage.py runserver -h
WARNING	2021-03-01 13:01:27,529	decorators.<module>	71	uwsgi module not found, tasks will run in threads	
usage: manage.py runserver [-h] [--ipv6] [--nothreading] [--noreload]
                           [--nostatic] [--insecure] [--version]
                           [-v {0,1,2,3}] [--settings SETTINGS]
                           [--pythonpath PYTHONPATH] [--traceback]
                           [--no-color] [--force-color]
                           [addrport]

Starts a lightweight Web server for development and also serves static files.

positional arguments:
  addrport              Optional port number, or ipaddr:port
```

**Comment by munchkindev** [comment]
I needed to add into ./biostar/settings.py in ALLOWED_HOSTS my IP/Domain and then using the command I managed to get it running, but it automatically loaded the recipes settings instead of forum, which I need, how can I change that?

**Comment by munchkindev** [comment]
Nevermind, figured it out - you need to change in manage.py the recipes part to forum and voilá it works
