### ISSUE TITLE
Changing default admin password does not seem to work, delete users and change/reset passwords

### ISSUE THREAD

**Issue by munchkindev** [ialbert/biostar-central#711]
So I tried changing the default admin username and password in /biostar/settings.py and when I run `python3 manage.py runserver 0.0.0.0:8000` the default username and password does still seem to exist.
Also, how do you delete users or change/reset their passwords?

**Comment by munchkindev** [comment]
Localization settings made in the file also seem to not take effect...

**Comment by ialbert** [comment]
passwords are set once, initially when the site is created, it won't reapply the passwords later if the user already exists.

if you need to change passwords later use the django admin command:

    python manage.py changepassword -h

Not sure what you mean by localization settings.

**Comment by munchkindev** [comment]
@ialbert I get the following output: ```
(engine) root@027254b87251:/data/biostar-central# python manage.py changepassword admin@localhost
Secrets module not imported: No module named 'conf.run.site_secrets'
WARNING 2021-03-02 14:21:05,540 decorators.<module>     71      uwsgi module not found, tasks will run in threads
CommandError: user 'admin@localhost' does not exist
```
I am 100% certain that the user admin@localhost exists and is the default admin.

By localization I mean the language settings for the app.

**Comment by ialbert** [comment]
forgot to mention, the way it works you need to access the username by username not email, the admin usernames are generated sequentially for each admin:

    python manage.py changepassword  admin-1

and so on.

There is no localization setting or maybe were are referring to different things. Localization usually means that the interface runs in different languages. The app is only available in English.

**Comment by munchkindev** [comment]
Is there also a possibility to change username names and to delete users

**Comment by ialbert** [comment]
there is really no need to change usernames, those are almost never used in Biostar (except this case). 

we also don't directly support deleting users, you can of course do it in the database and in the admin interface. Looks like we forgot to enable the admin interface on Biostar, I have just committed this change to enable it.

http://..../admin/

is the URL to the admin interface. 

If you are logged in as admin you can access all elements of the database.

when you delete a user in the admin interface you will see what other objects will get dropped (there is a cascading effect where all content that depends on a user will get automatically deleted as well: posts, votes, messages,) so deleting a user can have lots of consequences.

**Comment by munchkindev** [comment]
Brilliant, thank you :)
