### ISSUE TITLE
Collectstatic is not working when DEBUG is set FALSE

### ISSUE THREAD

**Issue by wMeloFernandes** [ialbert/biostar-central#744]
I'm working on Forum App. I set the DEBUG flag to FALSE. However when I start the server by 'make forum serve' the css files are not detected.

I run the command make forum init, the static files were generated in export/static folder. However is not been detected by the browser.

Do you have any ideas?

**Comment by ialbert** [comment]
when DEBUG is false you have to run collect static separately, this is how Django works:

https://docs.djangoproject.com/en/3.1/howto/static-files/deployment/
