### ISSUE TITLE
Error message when deleting comments

### ISSUE THREAD

**Issue by ATpoint** [ialbert/biostar-central#747]
See screenshot for the error message that comes up when deleting a comment via Edit-Delete:
The deletion seems to work but only after a refresh of the page.

<img width="788" alt="Screenshot 2021-03-22 at 13 39 01" src="https://user-images.githubusercontent.com/21218078/111993238-a8a72600-8b16-11eb-880d-e8cb50e1ba5b.png">

**Comment by ATpoint** [comment]
@Natay This works now for me without errors, guess we can close this one?

**Comment by Natay** [comment]
@ATpoint Yeah, this is resolved and can be closed

**Comment by ATpoint** [comment]
Perfect, thank you!
