### ISSUE TITLE
Sidebar shows raw HTML content of posts

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#751]
The website sidebar shows HTML content of similar posts. Screenshot below:

<img src="https://i.ibb.co/1bm7CTj/image.png" alt="image" border="0" />

**Comment by ialbert** [comment]
ah yes,  if you did not know, you can use latex in  biostar posts, thanks to @Natay 

copy this below into any answer (no need to submit just to see the preview):


When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

**Comment by Natay** [comment]
This issue has been fixed.
