### ISSUE TITLE
search is not working in version 2.3.5

### ISSUE THREAD

**Issue by pradipmudi** [ialbert/biostar-central#789]
Search is not working in version 2.3.5, is there anything that I've missed while configuring the project? 
Please help on this issue.

**Comment by ialbert** [comment]
You need to build the search index in a separate process, usually a cronjob will do

https://github.com/ialbert/biostar-central/blob/master/biostar/forum/management/commands/index.py

for testing just run 

python manage.py index --size 100

**Comment by pradipmudi** [comment]
Thanks @ialbert , it's working now. :)
