### ISSUE TITLE
HTML gets rendered as plain text on drag-drop

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#805]
Sample post: https://www.biostars.org/p/4176/#24405

I observed this once before but did not record it. This time, I captured the event. The post looked fine and then I moved it to a reply on a different comment and suddenly I see the `<p>....</p>` tags.

![](https://i.ibb.co/sqjrvnX/image.png)

**Comment by ialbert** [comment]
Some old posts may be stored as HTML and when moved it may trigger a re-parsing.

I think the way this should work here @Natay  is that when we move posts it we do not trigger the entire save signal.

**Comment by Natay** [comment]
The issue does come from re-parsing old posts, I will take out the signals triggering when posts are moved.

**Comment by Natay** [comment]
This issue has been fixed and deployed.
