### ISSUE TITLE
My account was reseted  or lost

### ISSUE THREAD

**Issue by geparada** [ialbert/biostar-central#845]
Hello there,

I have been using biostar for more than 10 years. For some reason, when I login with my gmail I can not longer enter to my original account. This is my original account:

https://www.biostars.org/u/1815/?active=profile

And now I can only enter a newly created account:
https://www.biostars.org/u/03856210/

I am not sure this is the right place to post this issue, but other users that do automatic login with google may be affected. 

Best,
Guillermo

**Comment by ialbert** [comment]
this is because your old account had a different email, and not the gmail account
