### ISSUE TITLE
Deny duplicate posts within a short time frame

### ISSUE THREAD

**Issue by ialbert** [ialbert/biostar-central#846]
No two identical posts should be permissible within a short window (say 1 minute). 

The above action would help avoid duplicate submissions due to server timeouts/lags. back button/resubmit etc. 

If a duplicate post is made (same author, same content < less than 1 minute) an error should be generated and the previous posts should be loaded/shown.

**Comment by Natay** [comment]
We have pushed out the above fix for this issue.
