### ISSUE TITLE
Login not working after deploying website

### ISSUE THREAD

**Issue by RodBelaFarin** [ialbert/biostar-central#876]
I was able to deploy my forum.

Unfortunately the login does not work.

I can register new users, but when I use the login, I am just redirected to the start page. If I enter wrong credentials the site tells me that user does not exist or password is wrong, but if both is correct, I get just redirect to start page without being logged in.

It works fine during my tests locally. What I found out is that a cookie "sessionid" is created locally after login, but this is not being created after deployment on the server.

The website is hosted here: 206.189.14.73

**Comment by ialbert** [comment]
this sounds like the host is not set correctly, 

cookies are set by hostname, not sure that you can set cookies by IP
