### ISSUE TITLE
relation "forum_post" does not exist

### ISSUE THREAD

**Issue by fangpingmu** [ialbert/biostar-central#878]
I have deployed biostar-central through uWSGI + nginx to a server. postgresql is used as the database. I have added DATABASE biostardb.

CREATE USER "www-forum" WITH ENCRYPTED PASSWORD '*****';
CREATE DATABASE biostardb;
GRANT ALL PRIVILEGES ON DATABASE biostardb TO "www-forum";

When I open a browser, I receive a programming error.

ProgrammingError at /

relation "forum_post" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "forum_post" INNER JOIN "f...
                                          ^
Are there something missing in my database setup?

**Comment by ialbert** [comment]
you have to run the migration to initialize the database

see the Makefile for how we set it all up:

    make init

https://github.com/ialbert/biostar-central/blob/master/Makefile#L96

**Comment by fangpingmu** [comment]
I am still getting this error after I run the two commands.

(base) [www-forum@forum biostar-central]$ python manage.py collectstatic --noinput -v 0 --settings biostar.forum.settings
Secrets module not imported: No module named 'conf.run.site_secrets'
INFO	2021-07-22 17:42:40,599	decorators.<module>	266	workers and timers set to block
(base) [www-forum@forum biostar-central]$ python manage.py collectstatic --noinput -v 0 --settings biostar.forum.settings
Secrets module not imported: No module named 'conf.run.site_secrets'
INFO	2021-07-22 17:43:40,290	decorators.<module>	266	workers and timers set to block
(base) [www-forum@forum biostar-central]$ python manage.py migrate -v 0 --settings biostar.forum.settings
Secrets module not imported: No module named 'conf.run.site_secrets'
INFO	2021-07-22 17:43:57,896	decorators.<module>	266	workers and timers set to block
INFO	2021-07-22 17:43:58,535	apps.init_site	112	db.name=/home/www-forum/biostar-central/export/db/database.db, db.engine=django.db.backends.sqlite3
INFO	2021-07-22 17:43:58,535	apps.init_site	113	email.backend=django.core.mail.backends.console.EmailBackend, email.sender=Admin User <admin@localhost>
INFO	2021-07-22 17:43:58,539	apps.init_site	123	site.name=Biostar Forum, site.domain=localhost
INFO	2021-07-22 17:43:58,541	apps.init_users	100	Admin user: admin@localhost already exists


/home/www-forum/biostar-central/conf/run/site_settings.py

DATABASE_NAME = "biostardb"

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': DATABASE_NAME,
        'USER': 'www-forum',
        'PASSWORD': '*******',
        'HOST': '/var/run/postgresql/',
        'PORT': '',
    },
}

Are I still missing something?
