### ISSUE TITLE
No posting guide

### ISSUE THREAD

**Issue by gksmyth** [ialbert/biostar-central#884]
Biostars seems no longer to have a posting guide.

Clicking on "New post" then on "Posting guide" leads to the error message "Post does not exist".

There is no mention of a posting guide on Biostar's "About" page, instead just a sentence of advice is given, so perhaps Biostars has abandoned the idea of a posting guide as a separate page? I had wanted to link to the guidelines in order to explain to a poster than they should include the relevant code in their question, not just the output.

**Comment by ialbert** [comment]
thanks for the note, weirdly we have that post gone, we will investigate

**Comment by alextrouerntrend** [comment]
I just closed a duplicate I made of this same issue.

**Comment by gksmyth** [comment]
Any progress in the past 18 months?

**Comment by ialbert** [comment]
to be honest, I had completely forgotten about this issue, sorry about that

Alas, we don't have a developer working on the main codebase at this time, so there is no one we could assign quality-of-life issues 

will only be fixed when a new major release is made - which might happen by the end of this year

**Comment by ialbert** [comment]
The link has been fixed. Better late than never.

**Comment by gksmyth** [comment]
Thanks, I think it's a valuable link to revive.
