### ISSUE TITLE
Cannot sign up.

### ISSUE THREAD

**Issue by MordorianGuy** [ialbert/biostar-central#900]
When I click sign up with email I see nothing.
![изображение](https://user-images.githubusercontent.com/100205963/155512150-56b0762b-a785-433b-b469-b4c287e200e4.png)

**Comment by ialbert** [comment]
that's pretty odd, what browser/operating system are you using? is it possible that you are blocking some parts of the page?

**Comment by MordorianGuy** [comment]
Sorry, I am a kind of stupid. AdBlock was turned on 🤦‍♂️
