### ISSUE TITLE
Language checking: Language "x" is not one of the supported languages

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#911]
This is an error I see often in posts that are all in English, with no accented characters even. An example post: https://www.biostars.org/p/165002/

Try editing it by replacing the `<p>BI=</p>` with `BI=` and you'll see the error on trying to save. I can't figure out why this happens or why it's solved in some cases (2-3 cases if memory serves right) when I replace triple backslash code blocks with 4-space prefix code blocks. It seems to be failing at this function: https://github.com/ialbert/biostar-central/blob/master/biostar/forum/forms.py#L35

This was earlier discussed (mentioned but the discussion seems incoherent) at #424 

Can you please look into this?

**Comment by ialbert** [comment]
this error happens when there is too much data and too little supporting text, 

the system cannot figure out the language. 

it is possible to turn off the check completely, 

we used to get a lot of spam in foreign languages - that's why the check has been put into place.

**Comment by RamRS** [comment]
I figured it had to do something with spam. I guess things can stay as they are - the benefit from fixing this won't be worth any change you make.

**Comment by RamRS** [comment]
Closing this.

**Comment by ialbert** [comment]
Setting the variable below to an empty list will turn off the language detection:

https://github.com/ialbert/biostar-central/blob/master/biostar/settings.py#L19
