### ISSUE TITLE
Cannot see error message while trying to create new post

### ISSUE THREAD

**Issue by RamRS** [ialbert/biostar-central#912]
I'm trying to create a new test post on biostars.org with the following content:

- Title: abcdef trial
- Type: Question/Forum (tried with both)
- Tags: a b,c,d,gene
- Content: 

trial
trial
trial
trial
trial
trial
trial
trial
trial

trial
trial
trial
trial
trial
trial
trial
trial
trial

trial
trial
trial
trial
trial
trial
trial
trial
trial

trial
trial
trial
trial
trial
trial
trial
trial
trial

The post does not get created. I see the post content box highlighted in red and the preview pane no longer showing a preview:

![screenshot][1]

What is the error I'm running into and why doesn't it show?

Not sure if this would help, but in the browser console, I see this message on hitting `Submit`:

```
Uncaught ReferenceError: field_label is not defined
    <anonymous> https://www.biostars.org/static/CACHE/js/output.034458da5d7d.js:33
    jQuery 2
        each
        each
    <anonymous> https://www.biostars.org/static/CACHE/js/output.034458da5d7d.js:32
    jQuery 13
        j
        k
        setTimeout handler*Deferred/then/g/<
        i
        fireWith
        fire
        i
        fireWith
        ready
        S
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
[output.034458da5d7d.js:33:42](https://www.biostars.org/static/CACHE/js/output.034458da5d7d.js)
    <anonymous> https://www.biostars.org/static/CACHE/js/output.034458da5d7d.js:33
    jQuery 2
        each
        each
    <anonymous> https://www.biostars.org/static/CACHE/js/output.034458da5d7d.js:32
    jQuery 13
        j
        k
        (Async: setTimeout handler)
    g
        i
        fireWith
        fire
        i
        fireWith
        ready
        S
        (Async: EventListener.handleEvent)
    <anonymous>
        <anonymous>
        <anonymous>
```

 [1]: https://i.ibb.co/2jNrbHQ/image.png

**Comment by ialbert** [comment]
I tried the reproduce but I did not get an error. 

What browser are you using? And what kind of extensions?

Can you reproduce with another browser (or with no extensions loaded)

Note that we have not changed the code on the main site for many months now

**Comment by RamRS** [comment]
I’m using Firefox with a great number of add-ons/extensions. I’ll try using Private Browsing (no extensions) as well as Safari (only one extension I think) and get back to you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RamRS** [comment]
Both Firefox (private browsing) and Safari on macOS replicate this behavior, including the JS error on `field_label`.

**Comment by ialbert** [comment]
let's ask some folks on Slack, 

for me on a Mac I tried with both Chrome and with Safari it seems to work with no errors

**Comment by IanSudbery** [comment]
I can replicate this, including the field_label error. 

Chrome 104.0.5112.81 on Windows 10. 

Extensions:
Application launcher for Drive, Chrome Remote Desktop, Google Docs offline, Google Keep Chrome Extension, LastPass, LeechBlock NG, LibKey Nomad, Mendeley Web Importer, RescueTime for Chrome, Snow Web Application Metering, uBlock Origin.

**Comment by RamRS** [comment]
The only extension in Ian’s list that I also use is uBlock Origin. But my Safari does not have that extension so I wonder why it runs into the same error.

**Comment by ialbert** [comment]
Errors should be displayed properly but will not go live right away - once things slow down.
