### ISSUE TITLE
What is the explanation of using following code?

### ISSUE THREAD

**Issue by arriyaz** [ialbert/biostar-central#919]
In the **Variant Calling Example** chapter following code was used to download the reference sequence from NCBI.

`efetch -db nuccore -format fasta -id $ACC | seqret -filter -sid $ACC > $REF`

While I can download the sequence by using the first part of the code:
`efetch -db nuccore -format fasta -id $ACC > $REF`

What is the function of the following second part? Is it really necessary?
`seqret -filter -sid $ACC`

Would you please breakdown this part of the code?
Thanks in advance.

**Comment by ialbert** [comment]
The reason for the remapping of the ID is to ensure that the resulting fasta file has the same id as the number we have requested it with.

for example fetching with `NC_045512` you will get a fasta file with the sequence id `NC_045512.2` and that could be confusing later on.

Some later tools use version-less sequence ids and I wanted to make sure the sequences are named the same.

Keeping sequences named the same is an ongoing challenge, many times tools fail to operate correctly when one sequence has a version and the other does not

**Comment by arriyaz** [comment]
Wow!! That's great. Thank you very much for the very nice explanation.
