### ISSUE TITLE
Biostar wouldn't post new question 

### ISSUE THREAD

**Issue by xinrant** [ialbert/biostar-central#926]
Hello, I'm trying to post a new question on biostar but the content box kept being red without telling me what is wrong with my code. I reviewed the posting guideline and still couldn't figure out why my post is not ok. PLEASE can someone tell me why?
<img width="848" alt="Screenshot 2023-10-19 at 11 45 19" src="https://github.com/ialbert/biostar-central/assets/62039763/4152af50-dc5d-44c0-a698-25f99fd34da2">

**Comment by ialbert** [comment]
you have invalid characters in the text, like arrows, it should show the error in a red box but because of a bug it does not

make sure you are posting text only, this includes the weird percents etc.

type the text into the windows, rather than copy pasting from word or other platforms

**Comment by ialbert** [comment]
As for the reason why we are so strict, unfortunately, spammers have found ways to generate all kinds of barely readable but decipherable content  using extended UTF characters that would pass normal spam detection, 

so we had to restrict to strictly text input.

The error reporting to well-meaning users has a flaw and can cause frustration like you experience; sorry about that; we'll try to fix it soon

**Comment by xinrant** [comment]
> As for the reason why we are so strict, unfortunately, spammers have found ways to generate all kinds of barely readable but decipherable content using extended UTF characters that would pass normal spam detection,
> 
> so we had to restrict to strictly text input.
> 
> the error detection and reporting has a flaw and causes frustration, we'll fix it soon

Thank you for the fast response! I'm able to post now!
