### ISSUE TITLE
Show "revisions" only if applicable

### ISSUE THREAD

**Issue by mkuhn** [ialbert/biostar-central#93]
The "revisions" link below each question/answer really only makes sense when there's more than one revision.

**Comment by standage** [comment]
The revisions link seems to have disappeared. Is that true or am I missing something, @ialbert?

**Comment by ialbert** [comment]
this has been removed last year - over the years the revisions feature has never been used on the other hand fixing up typos and other small edits just generate lots of useless revisions and use up space and CPU.
