### ISSUE TITLE
"What chapters cover the Zika Data" in the "Redo: Zika virus targets human cortical neural precursors" incorrect links

### ISSUE THREAD

**Issue by dgodin19** [ialbert/biostar-central#948]
I am reading through the Zika virus redo chapter of the biostar handbook, and would like to access the last three links in the section: 

[Understand the Zika data](https://www.biostarhandbook.com/zikaredo.html#rnaseq-zika-data)
[Alignment-based RNA-Seq of Zika data](https://www.biostarhandbook.com/zikaredo.html#rnaseq-zika-align)
[Classification-based RNA-Seq of Zika data](https://www.biostarhandbook.com/zikaredo.html#rnaseq-zika-classify)

However, clicking on the links leads to the Redo: Zika virus page. 

Are the correct links located in another book?

**Comment by ialbert** [comment]
looks like the links are not right, 

the correct links should be

* https://www.biostarhandbook.com/rnaseq-zika-data.html
* https://www.biostarhandbook.com/rnaseq-zika-align.html
* https://www.biostarhandbook.com/rnaseq-zika-classify.html

I will make the correction tomorrow.

I want to mention that  the RNA-Seq guides in the main book are a little outdated. The concepts are still correct, but the code should be substituted with that from either the **RNA-Seq by example** or the **Biostar Workflowa** book.

I will make the corrections and clarifications tomorrow,
